<?php

namespace Faker\Provider\id_ID;

class Person extends \Faker\Provider\Person
{
    protected static $maleNameFormats = array(
        '{{firstNameMale}} {{lastName}}',
        '{{titleMale}} {{firstNameMale}} {{lastName}}',
        '{{firstNameMale}} {{lastName}} {{suffix}}',
        '{{titleMale}} {{firstNameMale}} {{lastName}} {{suffix}}',
    );

    protected static $femaleNameFormats = array(
        '{{firstNameFemale}} {{lastName}}',
        '{{titleFemale}} {{firstNameFemale}} {{lastName}}',
        '{{firstNameFemale}} {{lastName}} {{suffix}}',
        '{{titleFemale}} {{firstNameFemale}} {{lastName}} {{suffix}}',
    );

    /**
     * @link http://www.nama.web.id/country-origin-Indonesia.html
     */
    protected static $firstNameMale = array(
        "Abdillah","Abdul","Abdul Aziz","Abil","Abyasa","Adam",
        "Adam Purwadi","Adam Putra Adnan","Adang","Adhikari","Adib",
        "Adibrata","Adiharja","Adika","Adikara","Adinata",
        "Aditya","Adiwangsa","Adiwarna","Adiwidya","Adiyatma",
        "Adjaya","Admaja","Adnan","Adriyanto","Agam",
        "Agung","Agus","Ahmad Fauzan","Ainun Nisa Putri","Aji",
        "Ajiman","Ajimat","Ajimin","Ajiono","Akarsana",
        "Akas","Akbar","Akik","Akmal","Alambana",
        "Alfa","Alif","Amat","Ambarawati","Amir",
        "Among","Andaka","Andani","Andhika","Andi",
        "Andilau","Andini","Angel","Anggabaya","Angkasa",
        "Angsana","Anindita Azarin","Anisa Adama","Anjali","Anjana",
        "Anom","Anteng","Anto","Anugerah","Ararya",
        "Arbani","Ardan","Ardhani","Ardi","Ardiman",
        "Ardiono","Ardiyanto","Arga","Argani","Argono",
        "Ari","Arifudin","Aris","Arjanti","Arkana",
        "Arnawama","Arsa","Artanto","Artawan","Aruna",
        "Arya","Aslijan","Asliman","Aslimin","Asma",
        "Asmadi","Asmar","Asmawa","Asmaya","Asmianto",
        "Asoka","Assegaf","Astami","Astamurti","Astangga",
        "Astatanu","Astatik","Aswanda","Aswangga","Aswani",
        "Aswono","Atharwa","Atmaja","Atmajaya","Atmaranti",
        "Atmariani","Ato","Awaludin","Awan","Ayem",
        "Azhar","Aziz","Babaran","Bada","Baden",
        "Badruddin","Badrun","Bagas","Bagiya","Bagong",
        "Bagus","Bagya","Bahana","Bahri","Bahuraksa",
        "Bahuwarna","Bahuwirya","Baja","Bajragini","Bakda",
        "Bakiadi","Bakianto","Bakidin","Bakijan","Bakiman",
        "Bakiono","Bakti","Baktiadi","Baktianto","Baktiono",
        "Bala","Balamantri","Balapati","Balapradhana","Balawanta",
        "Balen","Bales","Bali","Balidin","Balijan",
        "Balila","Balin","Balqissa Aretha","Baluku","Bambang",
        "Banara","Banawa","Banawi","Bancana","Bancar",
        "Banda","Bandha","Bandhawa","Bandiani","Bandiman",
        "Bandinah","Bandini","Bandri","Bandrianto","Bandriya",
        "Bandul","Bang Joni","Bangkit","Banu","Bara",
        "Barat","Barata","Bardiman","Bardimin","Bardinah",
        "Bardiono","Barep","Bari","Baridin","Barijan",
        "Bariman","Basi","Basirah","Basiran","Baskara",
        "Basuki","Basunjaya","Basupati","Basurata","Baswara",
        "Batara","Batari","Bataria","Baupati","Baureksa",
        "Bawa","Bawana","Bawita","Bayu","Becik",
        "Begawan","Bela","Belani","Bener","Berlian",
        "Besariono","Bhadra","Bhagaskara","Bhagawanta","Bhaksana",
        "Bhranta","Bianglala","Bibit","Bilas","Bilis",
        "Bima","Bintang","Bisma","Bismaka","Blaster",
        "Boma","Boncot","Bondan","Bramanty","Branjang",
        "Brant","Branta","Brantandari","Brata","Bratadikara",
        "Bratajaya","Bratanjali","Bratawati","Brojol","Brujul",
        "Bruno","Buana","Bubut","Budaya","Budi",
        "Budiani","Budianto","Budiarno","Budiman","Budiono",
        "Bulan","Bumi","Bumiputra","Bunga","Bungah",
        "Bungkus","Buntala","Buntaran","Buntardi","Buntari",
        "Buntarno","Buntarto","Burke","Burna","Burnadi",
        "Burnanto","Butul","Buyut","Byakta","Cagak",
        "Cager","Cahya","Cahyadi","Cahyanto","Cahyono",
        "Caket","Cakra","Cakrabirawa","Cakrabuana","Cakradara",
        "Cakrajiya","Cakrawala","Cakrawangsa","Camar","Candra",
        "Candrakanta","Candrakanti","Candraningsih","Candrarupa","Candrawimba",
        "Candrika","Capa","Caraka","Carter","Carub",
        "Catur","Caturangga","Cawis","Cawisadi","Cawisono",
        "Cawuk","Cayadi","Cayapata","Cecep","Cekap",
        "Cekel","Cendekia","Ceplis","Ceta","Chen",
        "Cikal","Cinde","Cindur","Cira","Cita",
        "Citra","Conary","Cucup","Cumbu","Cunduk",
        "Curibrata","Curiga","Curik","Dacin","Dadah",
        "Dadap","Dadi","Dagel","Dali","Daliani",
        "Dalimah","Daliman","Dalimin","Daliono","Dalirin",
        "Dalu","Damar","Dami","Damu","Dana",
        "Daniswara","Danu","Danuja","Danumaya","Danurdara",
        "Darijan","Darimin","Darma","Darmaji","Darman",
        "Darmana","Darmani","Darmanto","Darsirah","Dartono",
        "Daru","Daruna","Dasa","Dasuki","Dava",
        "David","Deden","Dedi","Dewa","Dewangga",
        "Dian","Digdaya","Dila","Dimas","Dipa",
        "Dirja","Dofit","Dona","Drajat","Duloh",
        "Dwi","Edi","Egi","Eka","Elok",
        "Elon","Eluh","Elus","Eman","Emas",
        "Embuh","Emong","Empluk","Endah","Endang",
        "Endra","Enjen","Enteng","Entik","Eri",
        "Eris","Esa","Estiawan","Estiono","Estu",
        "Fadey","Fadhuli","Fadil","Fahd","Fahri",
        "Faisal","Fajar","Fajari","Fakhir","Firus",
        "Fitrah","Fitriani","Frederica Harfifa","Gada","Gadang",
        "Gading","Gaduh","Gaharu","Gaimah","Gaiman",
        "Galak","Galang","Galar","Gali","Galib",
        "Galih","Galiono","Galuh","Galur","Gaman",
        "Gamani","Gamanto","Gambira","Gamblang","Ganda",
        "Gandes","Gandewa","Gandi","Gandik","Gandon",
        "Gandring","Ganep","Gangsa","Gangsar","Ganjaran",
        "Ganjiran","Ganjur","Gantar","Gara","Garan",
        "Garang","Garda","Garini","Gas","Gati",
        "Gatot","Gatra","Gatuk","Gayatri","Gelar",
        "Gema","Gemana","Gemani","Gemi","Gemilang",
        "Gemuruh","Gendut","Genjah","Genta","Gentala",
        "Gepeng","Gesang","Gilang","Giono","Girah",
        "Giras","Girasto","Giyanto","Giyarto","Giyati",
        "Giyono","Gogor","Graha","Gunadi","Gunamin",
        "Gunarsih","Gunawan","Guntur","Gupi","Guritna",
        "Gurna","Gurnita","Guruh","Guruh Esa Setia","Gusti",
        "Hadyan","Halab","Halabi","Haladara","Halayuda",
        "Hali","Halib","Halibab","Halilintar","Haliman",
        "Halimi","Halin","Haliwar","Halu","Hamdani",
        "Hamid","Hamun","Hana","Hanafi","Handaru",
        "Hanteb","Haras","Hardana","Hardi","Hari",
        "Harimurti","Haris","Harita","Harja","Harjanti",
        "Harjasa","Harjaya","Harsana","Harsaya","Hartaka",
        "Hartana","Hartati","Haru","Haryadi","Hasan",
        "Hasta","Hastungkoro","Hastuti","Hawa","Hawan",
        "Hemas","Hengkara","Hening","Heri","Heru",
        "Himawan","Hudor","Huntara","Ibrit","Icuk",
        "Idin","Iffat","Ihsan","Ilal","Ilir",
        "Ilu","Ilyas","Imad","Imam Saputera","Imu",
        "Indah","Indra","Indriani","Indun","Irfansyah",
        "Irsad","Izi","Jabal","Jabir","Jaeman",
        "Jaga","Jagapati","Jagaraga","Jail","Jaka",
        "Jaladara","Jalal","Jalu","Jamal","Jamalludin",
        "Jamil","Jamus","Jana","Janadi","Jani",
        "Janimah","Jariani","Jariati","Jarih","Jariya",
        "Jarna","Jarumah","Jarwa","Jarwadi","Jarwani",
        "Jarwi","Jasmani","Jaswadi","Jaswi","Jati",
        "Jatmika","Jatmiko","Jaya","Jayadi","Jayeng",
        "Jelawardi","Jenar","Jidan","Jimmy","Jinah",
        "Jinawi","Jindra","Jinem","Jingga","Johar",
        "Juandi","Julia Amelia","Jumadi","Jumari","Jumi",
        "Kacung","Kadali","Kadar","Kadi","Kaftan",
        "Kagendra","Kahfi","Kahrab","Kaimat","Kaisar",
        "Kajar","Kaji","Kalantara","Kalimantang","Kalis",
        "Kalpana","Kamali","Kamandaka","Kamani","Kambala",
        "Kamidin","Kamil","Kamirah","Kandi","Kangsa",
        "Kani","Kanjar","Kari","Kariman","Karimullah",
        "Karja","Karkasa","Karma","Karmi","Karna",
        "Karsa","Karsana","Karsani","Karta","Karti",
        "Kartika","Kartini","Karun","Kasapi","Kasiran",
        "Kasmirah","Kasti","Kasub","Kawaca","Kawadi",
        "Kawaya","Kawista","Kayi","Kayun","Kedasih",
        "Kemba","Kenang","Kenar","Kenes","Kerama",
        "Kesara","Kesarja","Kidung","Kikis","Kinasih",
        "Kirmizi","Komar","Kosali","Kosasih","Kostuba",
        "Kumuda","Kuncara","Kundali","Kunthara","Kupita",
        "Kuranta","Kusala","Kusara","Kusuma","Kuwaka",
        "Labas","Labuh","Laila Wulandari","Lajawardi","Laksana",
        "Lali","Lamar","Lanang","Langgeng","Lanjar",
        "Lantar","Las","Lasmadi","Lasmanto","Lati",
        "Lawana","Lawat","Lazuardi","Lega","Legawa",
        "Legi","Lembah","Lemet","Lepamaya","Lestari",
        "Lewih","Ligar","Lila","Liman","Limar",
        "Lintang","Lipur","Loma","Lopa","Luh",
        "Luhtitisari","Luhung","Lukita","Lukman Hakim","Luluh",
        "Lulut","Lurhur","Luruh","Lurun","Lurus",
        "Luwar","Luwes","Madhura","Maga","Mahadana",
        "Mahajana","Mahesa","Mahira","Makara","Makuta",
        "Malini","Malya","Mandala","Mandateja","Manggali",
        "Mangkin","Manguri","Manikam","Mantri","Maras",
        "Mardiah","Margana","Mari","Mariadi","Marmara",
        "Marsudi","Marta","Martaka","Martana","Maryani",
        "Maryanti","Maryanto","Mas Ruha","Nara","Pandu",
        "Panglima","Panji","Patah","Pijar","Prasista",
        "Pribadi","Rabun","Saban","Samapta","Samudra",
        "Sigi","Sudana","Sumantri","Sura","Sutra",
        "Tadi","Tanda","Tangguh","Tangkas","Tani",
        "Tanjung","Teja","Tusta","Udayana","Ugraha",
        "Zeni","Zohor",
    );

    /**
     * @link http://www.nama.web.id/country-origin-Indonesia.html
     */
    protected static $firstNameFemale = array(
        "Aay","Abbas","Abdillah","Abidah","Adah",
        "Adine","Adiratna","Adriyani","Adriyari","Afifa",
        "Agnes Anindita","Aini","Ajeng","Aliah","Alifia Arif",
        "Alisa","Amanda","Amarita","Ambar","Ambarawati",
        "Ambarningsih","Ambarsari","Ambarwati","Amelia","Ami",
        "Amira","An","Ana","Anabela","Ananda",
        "Anaya","Andaru","Andini","Andiyanti","Angel",
        "Anggi","Anggun","Anida","Anila","Anindia",
        "Anindita","Aninditha Avera","Anindya","Aniridya","Antya",
        "Anya","Anyango","Ara","Aras","Arawinda",
        "Ardhiona","Ardiana","Ardiningrum","Ardiyanti","Aretha",
        "Ariana","Ariani","Ariindya","Arini","Arip",
        "Arisanti","Aristawati","Arjana","Arjani","Arjanti",
        "Arpani","Arta","Artami","Artanti","Arum",
        "Arundari","Arundati","Arundaya","Aryama","Aryanti",
        "Asancaya","Asanggata","Asanka","Ashadewi","Ashaki",
        "Asih","Asipattra","Asirwada","Asliani","Aslimah",
        "Asmaranti","Asmarini","Asmawati","Asmiani","Asmiasih",
        "Asminah","Asmirah","Asmuni","Aspirin","Assifa",
        "Astagina","Astama","Astamurti","Astaseni","Astreila",
        "Astrella","Astuti","Astutiningsih","Astutiningtyas","Aswari",
        "Aswati","Aswini","Athalia","Atikah","Atma",
        "Atmarini","Atmawati","Atresia","Avera","Avera Lenita",
        "Ayla","Ayo","Ayu","Ayunda","Ayusman",
        "Azarin Astreila","Azighah Cahyani","Azizah","Badi’ah","Bahar",
        "Bajroyekti","Bala","Balerina Salasika","Ballerina","Balqis",
        "Barkah","Basilia","Basilia Azizah","Basilla","Bawika",
        "Beha","Bela","Belawati","Belia","Belia Rahayu",
        "Bendari","Bening","Berhane","Besariyanti","Bhanurasmi",
        "Bhanuwati","Bilkis","Binar","Bintang","Bintarti",
        "Budi Asih","Budiati","Bunga","Cahaya","Cahya",
        "Cahyani","Cahyaningrum","Cahyarini","Cakrawati","Calandara",
        "Calya","Candana","Candani","Candrakanti","Candraningsih",
        "Candraningtyas","Candrarini","Candrasmurti","Cantik","Carani",
        "Cararini","Carika","Catra","Catur Pratiwi","Cayarini",
        "Cemara","Cemerlang","Cempaka","Cenderawasih","Cepaka",
        "Chaitra","Chanda","Chanya","Chika","Chila",
        "Cicik","Citranti","Citrawati","Citrshayi","Clematis",
        "Dalal","Dalianti","Damayanti","Dara","Darapuspita",
        "Daria","Dariani","Dariati","Darliah","Darmastuti",
        "Darminah","Darmingtyas","Darsa","Darsiati","Darsini",
        "Darti","Dartinah","Daryana","Daryani","Datyani",
        "Dawi","Dayanti","Dayita","Delima","Denis Bilqisa",
        "Dewani","Dewati","Dewi","Dewi Purwati","Dewi Wulandari",
        "Dhia","Dian","Dianti","Dihyan","Diyanci",
        "Duhita Rukma Wati","Duta","Dzakiyah","Eka","Eli",
        "Eliana","Eliyanca","Eliyani","Elok","Elviana",
        "Elviana Cahyani","Emeliana","Emi","Emilia","Endah",
        "Endang","Enesia","Eriati","Erina","Erlinda",
        "Erna","Erum","Estiana","Estiningtyas","Eti",
        "Ezzah","Fadilah","Fahmi","Fahmida","Fairuz",
        "Faizah","Fakihah","Fani","Fatima","Fatin",
        "Faustina","Feby","Fira","Fleurette","Fredela Cahyani",
        "Gadis","Gagah","Galuh","Games","Gandari",
        "Ganica","Garini","Gayatri","Gendis","Genduk",
        "Gita","Giyanti","Gunarti","Gupita","Hala",
        "Hamzah","Hara","Hardiyani","Hardiyanti","Hardiyanti Rahmah",
        "Harina","Haritala","Haryati","Hasanti","Hasta",
        "Hastha","Hastu","Hastuti","Hasya","Hayu",
        "Her","Hikmah","Hindun","Idi","Iffah",
        "Iffah Astuti","Iim","Ika","Ikana","Ikari",
        "Ikawati","Ikurasu","Ina","Inasih Dewi Pujiastuti","Indah",
        "Indah Fadillah","Indrastuti","Indri","Indriani","Innayah",
        "Inong","Intan","Ira","Iswara","Jajar",
        "Jalada","Janirah","Jasma","Jayanti","Jelita",
        "Juantika","Julinah","Jumainah","Jumantara","Juminah",
        "Juwita","Kacaya","Kadawi","Kamal","Kamelia Azzahra",
        "Kana","Kani","Karisma","Karni","Kartika",
        "Kartini","Kasih","Kasmirah","Kasti","Kasturi",
        "Keisya Laksmi Maheswari","Kejora","Kemala","Kemuning","Kenanga",
        "Kenari","Kessie","Kibibi","Kidung","Kijan",
        "Kiki","Kinanti Ayu Putri","Kirna","Kokom","Komariah",
        "Kumala","Kumara","Kusuma","Kusumastuti","Laksmi",
        "Laksmiwati","Lala","Laras","Laris","Las",
        "Lasmani","Lasminah","Lasmirah","Lawar","Laya",
        "Lejar","Lela","Lembayung","Lena","Lenita",
        "Lentera","Lepana","Likah","Lili","Linda",
        "Lintang","Lirih","Lisah","Lituhayu","Locita",
        "Lola","Lolita","Lugia","Lyan","Lyle",
        "Mabir","Macika","Madah","Madhurya","Madira",
        "Magani","Magdalena Anastasia","Mahadri","Maharani","Mahardika",
        "Mahasura","Mahawira","Mahawirya","Maheswara","Mahsa Anindya",
        "Maja","Majaya","Manah","Manila","Manis",
        "Manyari","Marhunah","Mariana","Marici","Marma",
        "Marselina","Marta","Martani","Martini","Martyani",
        "Marwata","Maryadi","Maryani","Maryanti","Maya",
        "Mega","Mestika","Mirah","Sakura","Samita",
        "Sentana","Seruni","Setu","Sigra","Sila",
        "Sinar","Subur","Umbar","Yuwana",
    );

    protected static $lastName = array(
        // Batak, http://id.wikipedia.org/wiki/Daftar_marga_suku_Batak_di_Toba
        "Banjarnahor","Dabukke","Damanik","Doloksaribu","Dongoran","Harianja","Haro",
        "Hasibuan","Hutabarat","Hutagalung","Hutagaol","Hutahaean","Hutajulu",
        "Hutapea","Hutasoit","Malau","Manalu","Mangunsong","Manihuruk",
        "Manik","Manullang","Manungkalit","Manurung","Marbun","Marpaung",
        "NAIBORHU Naibaho","Nababan","Nadapdap","Nadeak","Nainggolan","Naipospos",
        "Napitupulu","Ompusunggu","Pakpahan","Pangaribuan","Panggabean","Panjaitan",
        "Pardede","Pardosi","Pasaribu","Pohan","Purba","Rajagukguk",
        "Rumahorbo","Rumapea","Samosir","Saragih","Sarumpaet","Siagian",
        "Siahaan","Sialagan","Sianipar","Sibarani","Sibuea","Sidabutar",
        "Sidauruk","Sihite","Sihombing","Sihotang","Sijabat","Silaban",
        "Silaen","Silalahi","Silitonga","Simamora","Simangunsong","Simanjuntak",
        "Simanungkalit","Simare-mare","Simarmata","Simbolon","Sinaga","Sinambela",
        "Sinurat","Sipahutar","Sirait","Siregar","Sitanggang","Sitindaon",
        "Sitinjak","Sitohang","Sitompul","Sitorus","Situmeang","Situmorang",
        "Tamba","Tarihoran","Turnip",

        // Nias, http://id.wikipedia.org/wiki/Daftar_marga_Nias
        "Amazihönö. Amuata","Baeha","Baene","Baewa","Bago","Bali","Bate'e","Bawa'ulu",
        "Bawamenewi","Bawaniwa'ö","Bawö","Bazikho","Bidaya","Bohalima","Bu'ulölö",
        "Buaya","Bulu'aro","Bunawölö","Dachi","Daeli","Dawölö","Daya",
        "Dohare","Dohude","Dohöna","Duha","Duho","Fa'ana,Famaugu","Fakho",
        "Falakhi","Fanaetu","Farasi","Fau","Finowa'a","Gaho","Gaidö",
        "Ganumba","Garamba","Gari","Gaurifa","Ge'e","Gea","Giawa",
        "Gohae","Gori","Gowasa","Gulö","Hadiranto","Hala Wawa","Halawa",
        "Harefa","Haria","Harimao,Halu","Harita","Hia","Hondrö","Hoya",
        "Hulu","Humendru","Hura","La'ia","Laeru","Lafau","Lahagu",
        "Lahömi","Lamölö","Laoli","Laowö","Larosa","Lasara","Lase",
        "Lature","Lawelu","Laweni","Lawölö","Lazira","Lo'i","Luaha",
        "Luahambowo","Lugu","Lömbu","Löndu go'o","Maduwu","Manaö","Maru'ao",
        "Maruabaya","Maruhawa","Marulafau","Marunduri","Mendröfa","Möhö","Mölö",
        "Nadoya","Nakhe","Nazara","Ndraha","Ndruru","Nehe","Ote",
        "Sa'oiagö","Sadawa","Saota","Saro","Sarumaha","Sihura","Sihönö",
        "Sisökhi","Taföna'ö","Tajira","Talunohi","Telaumbanua","Wakho","Waoma",
        "Warae","Warasi","Waruwu","Wau","Wehalö","Wohe","Zagötö",
        "Zai","Zalukhu","Zalögö","Zamago","Zamago zamauze","Zamasi","Zamili",
        "Zandroto","Zebua","Zega","Zendratö","Zidomi","Ziliwu","Ziraluo","Zörömi",

        // Manado, http://annsilva.wordpress.com/2009/09/13/marga-orang-manado/
        "Abutan","Adam","Agou","Akai","Aling","Alui","Amoi",
        "Andu","Anes","Angkouw","Anis","Antou","Arina",
        "Assah","Awondatu","Awui","Batas","Bella","Bokau",
        "Bokong","Bolang","Bolung","Bororing","Boyoh","Buyung",
        "Damongilala","Damopoli","Dapu","Datu","Datumbanua","Dayoh",
        "Dededaka","Dendeng","Dengah","Dewat","Dien","Dimpudus",
        "Dipan","Dompis","Dondo","Dondokambei","Donsu","Doodoh",
        "Doringin","Dotulong","Dumais","Dumanauw","Dumbi","Dungus",
        "Dusaw","Egam","Egetan","Ekel","Elean","Eman",
        "Emor","Endei","Engka","Enoch","Ering","Ganda",
        "Gerung","Gerungan","Gigir","Gimon","Girot","Goni",
        "Goniwala","Gonta","Gosal","Gumalag","Gumansing","Gumion",
        "Ilat","Imbar","Inarai","Ingkiriwang","Inolatan","Intama",
        "Item","Kaat","Kaawoan","Kaendo","Kaeng","Kaes",
        "Kainde","Kairupan","Kalalo","Kalangi","Kalempou","Kalempouw",
        "Kalengkongan","Kalesaran","Kalici","Kaligis","Kalitow","Kaloh",
        "Kalonta","Kalumata","Kamagi","Kambey","Kambong","Kamu",
        "Kandio","Kandou","Kapantouw","Kaparang","Kapele","Kapoh",
        "Kapoyos","Karamoy","Karau","Karinda","Karundeng","Karuyan",
        "Karwur","Kasenda","Katopo","Katuuk","Kaunang","Kawatu",
        "Kawengian","Kawilarang","Kawulusan","Kawung","Kawuwung","Keincem",
        "Kekung","Keles","Kelung","Kembal","Kembau","Kembuan",
        "Kenap","Kepel","Kerap","Kere","Kesek","Kewas",
        "Khodong","Kilapong","Kindangen","Kirangen","Kiroiyan","Kodongan",
        "Kojongian","Koleangan","Kolibu","Koloday","Koly","Komaling",
        "Kondoi","Kontul","Kopalit","Koraah","Korah","Korengkeng",
        "Korompis","Koropitan","Korouw","Korua","Kotambunan","Kountud",
        "Kowaas","Kowonbon","Kowu","Kowulur","Koyansouw","Kuhu",
        "Kulit","Kullit","Kumaat","Kumaunang","Kumayas","Kumendong",
        "Kumolontang","Kumontoy","Kupon","Kusen","Kusoi","Lala",
        "Lalamentik","Lalowang","Lalu","Laluyan","Lambogia","Lampah",
        "Lampus","Lanes","Langelo","Langi","Langitan","Langkai",
        "Languyu","Lantang","Lantu","Laoh","Lapian","Lasut",
        "Legi","Legoh","Lembong","Lempas","Lempou","Lengkey",
        "Lengkoan","Lengkong","Lensun","Leong","Lepar","Lesar",
        "Lewu","Liando","Limbat","Limbong","Limpele","Lincewas",
        "Lintang","Lintong","Liogu","Litow","Liu","Liwe",
        "Loho","Loing","Lolombulan","Lolong","Lomboan","Lompoliu",
        "Lonan","Londa","Londok","Longdong","Lontaan","Lontoh",
        "Losung","Lowai","Lowing","Ludong","Lumanau","Lumangkun",
        "Lumatau","Lumempouw","Lumenta","Lumentut","Lumi","Lumingas",
        "Lumingkewas","Lumintang","Luminuut","Lumoindong","Lumondong","Lumowa",
        "Lumunon","Luntungan","Lutulung","Maengkom","Maengkong","Mailangkai",
        "Mailoor","Maindoka","Mainsouw","Mait","Makadada","Makal",
        "Makaley","Makaliwe","Makangares","Makaoron","Makarawis","Makarawung",
        "Makatuuk","Makawalang","Makawulur","Makiolol","Makisanti","Malingkas",
        "Mamahit","Mamangkey","Mamantouw","Mamanua","Mamarimbing","Mamba",
        "Mambo","Mambu","Mamengko","Mamentu","Mamesah","Mamoto",
        "Mamuaya","Mamuntu","Mamusung","Manalu","Manampiring","Manangkod",
        "Manapa","Manarisip","Manaroinsong","Manayang","Mandagi","Mandang",
        "Mandey","Manebu","Manese","Mangare","Mangempis","Mangindaan",
        "Mangkey","Mangowal","Mangundap","Manimporok","Manopo","Manorek",
        "Mantik","Mantiri","Mantoauw","Manua","Manurip","Manus",
        "Mapaliey","Maramis","Marentek","Maringka","Masie","Masinambau",
        "Masing","Masoko","Matindas","Maukar","Mawei","Maweru",
        "Mawikere","Mawuntu","Mekel","Mema","Mende","Mendur",
        "Mengko","Mentang","Mentu","Mesak","Mewengkang","Mewoh",
        "Mince","Mincelungan","Minder","Mingkid","Mogot","Mokalu",
        "Mokolensang","Mokorimban","Momongan","Momor","Momuat","Mondigir",
        "Mondong","Mondoringin","Mondou","Mongi","Mongilala","Mongisidi",
        "Mongkaren","Mongkau","Mongkol","Mongula","Moniaga","Moninca",
        "Moningka","Moniung","Mononimbar","Mononutu","Montolalu","Montong",
        "Montung","Motto","Muaya","Mudeng","Mukuan","Mumek",
        "Mumu","Mundung","Muntu","Muntu untu","Muntuan","Musak",
        "Mussu","Nangka","Nangon","Nangoy","Naray","Nayoan",
        "Nelwan","Nender","Ngala","Ngangi","Ngantung","Ngayouw",
        "Ngion","Ogi","Ogot","Ogotan","Oleng","Oley",
        "Ombeng","Ombu","Ompi","Ondang","Onsu","Opit",
        "Oroh","Otay","Paat","Pai","Paila","Pakasi",
        "Palangiten","Palar","Palenewen","Palenteng","Palilingan","Palit",
        "Panambunan","Panda","Pandean","Pandelaki","Pandey","Pandi",
        "Pandong","Pangalila","Pangau","Pangemanan","Pangila","Pangkerego",
        "Pangkey","Pantonuwu","Pantouw","Parengkuan","Paruntu","Paseki",
        "Pasla","Pauner","Pele","Pelengkahu","Pendang","Pepah",
        "Pesik","Pesot","Piay","Pinangkaan","Pinantik","Pinaria",
        "Pinontoan","Pioh","Piri","Pitong","Pitoy","Podung",
        "Pola","Poli","Polii","Polimpong","Politon","Poluakan",
        "Pomantouw","Ponamon","Pondaag","Pongayouw","Ponggawa","Pongilatan",
        "Pongoh","Ponosingon","Pontoan","Pontoh","Pontororing","Poraweouw",
        "Porayouw","Porong","Posumah","Potu","Poyouw","Pua",
        "Pungus","Punuh","Purukan","Pusung","Putong","Raintung",
        "Rambi","Rambing","Rambitan","Rampangilei","Rampen","Rampengan",
        "Ransun","Ranti","Rantung","Raranta","Rares","Rarun",
        "Rasu","Ratag","Ratu","Ratulangi","Ratumbuisang","Ratuwalangaouw",
        "Ratuwalangon","Ratuwandang","Rau","Rauta","Regar","Rei",
        "Rembang","Rembet","Rempas","Rengku","Rengkuan","Rengkung",
        "Repi","Retor","Rimper","Rindengan","Rindo-rindo","Robot",
        "Rogahang","Rogi","Rolangon","Rolos","Rombot","Rompas",
        "Rompis","Rondo","Rondonuwu","Rooro","Rori","Rorimpandey",
        "Roring","Rorintulus","Rosok","Ruaw","Ruidengan","Rumagit",
        "Rumambi","Rumampen","Rumampuk","Rumayar","Rumbay","Rumende",
        "Rumengan","Rumenser","Rumimpunu","Rumincap","Rumokoy","Rumpesak",
        "Runturambi","Salangka","Salendu","Sambouw","Sambuaga","Sambul",
        "Sambur","Samola","Sangkaeng","Sangkal","Sarapung","Saraun",
        "Sarayar","Sariowan","Sarundayang","Saul","Seke","Seko",
        "Sembel","Sembung","Semeke","Senduk","Sengke","Sengkey",
        "Senouw","Sepang","Sigar","Sigarlaki","Simbar","Simbawa",
        "Sinaulan","Singal","Singkoh","Sinolungan","Sirang","Siwu",
        "Siwy","Solang","Somba","Sompi","Sompotan","Sondakh",
        "Soputan","Sorongan","Suak","Sualang","Suatan","Sumaiku",
        "Sumakud","Sumakul","Sumangkud","Sumanti","Sumarandak","Sumarauw",
        "Sumele","Sumendap","Sumesei","Sumilat","Sumlang","Sumolang",
        "Sumual","Sumuan","Sundah","Sungkudon","Suot","Supit",
        "Surentu","Suwu","Taas","Tairas","Talumepa","Talumewo",
        "Tambahani","Tambalean","Tambarici","Tambariki","Tambayong","Tambengi",
        "Tambingon","Tamboto","Tambun","Tambunan","Tambuntuan","Tambuwun",
        "Tamon","Tampa","Tampanatu","Tampanguma","Tampemawa","Tampenawas",
        "Tampi","Tampinongkol","Tandayu","Tangka","Tangkere","Tangkow",
        "Tangkudung","Tangkulung","Tanod","Tanor","Tanos","Tarandung",
        "Taroreh","Taulu","Tawas","Tendean","Tengges","Tenggor",
        "Tengker","Terok","Tidayoh","Tiendas","Tikoalu","Tikonuwu",
        "Tilaar","Timbuleng","Timpal","Tinangon","Tindengen","Tintingon",
        "Tirayoh","Tiwa","Tiwow","Toalu","Todar","Togas",
        "Tololiu","Tombeng","Tombokan","Tompodung","Tompunu","Tongkeles",
        "Tooi","Torar","Torek","Towo","Tuegeh","Tuera",
        "Tulandi","Tular","Tulenan","Tulung","Tulus","Tulusan",
        "Tumanduk","Tumangkeng","Tumatar","Tumbei","Tumbelaka","Tumbol",
        "Tumbuan","Tumembouw","Tumengkol","Tumewu","Tumilaar","Tumilesar",
        "Tumimomor","Tumiwa","Tumiwang","Tumober","Tumondo","Tumonggor",
        "Tumundo","Tumurang","Tumuyu","Tunas","Tundalangi","Tungka",
        "Turang","Turangan","Tuwaidan","Tuyu","Tuyuwale","Uguy",
        "Ukus","Ulaan","Umbas","Umboh","Umpel","Undap",
        "Unsulangi","Untu","Waani","Wagei","Wagiu","Waha",
        "Wahon","Wakari","Wala","Walalangi","Walanda","Walandouw",
        "Walangitan","Walean","Walebangko","Walelang","Waleleng","Walian",
        "Walintukan","Waluyan","Wanei","Wangania","Wangko","Wantah",
        "Wantania","Wantasen","Wariki","Watah","Watti","Watugigir",
        "Watuna","Watung","Watupongoh","Waturandang","Watuseke","Wauran",
        "Wawoh","Wawointama","Wawolangi","Wawolumaya","Waworuntu","Weku",
        "Welong","Wenas","Wenur","Weol","Wetik","Wilar",
        "Winerungan","Winokan","Woimbon","Wokas","Wola","Wondal",
        "Wongkar","Wonok","Wonte","Wooy","Worang","Worotikan",
        "Wotulo","Wowilang","Wowor","Wuisan","Wuisang","Wulur",
        "Wungkana","Wungow","Wuntu","Wurangian","Wuwung","Wuwungan",

        // Tionghoa, http://www.tionghoa.info/marga-tionghoa-di-indonesia/
        "An","Ang","Auw","Aw","Boen","Chang","Chee","Chi","Djie","Go","Goh",
        "Gouw","Han","Injo","Inyo","Jo","Kang","Kho","Khoe","Khouw","Kwee",
        "Kwik","Lee","Li","Lie","Liem","Lim","Liok","Liuk","Lo","Loe",
        "Lou","Lu","Luo","Ng","Nio","Njio","Njoo","Nyoo","Oei","Oen",
        "Oey","Ong","Ro","Seng","Seto","Shui","Sie","Siehu","Sieto","So",
        "Soe","Souw","Suhu","Swee","Szeto","Tan","Te","Teo","The","Theo",
        "Thio","Tio","Tjan","Tjhie","Tjhin","Tjia","Tjoa","Tjong","Tsang","Tsui",
        "Woen","Wong","Wu","Yap","Yo","Yong",

        // Ambon, http://latumeten717718.blogspot.com/2012/07/daftar-nama-marga-fam-di-ambon.html
        // 15 names out of each letter in the alphabet
        "Abarua","Abednego","Abel","Abraham","Abrahams","Abrahamsz",
        "Acher","Ademiar","Adeo","Adjahary","Adolf",
        "Adonis","Adriaansz","Adrian","Adrians","Adrianus",
        "Adrianz","Adtjas","Afaratu","Afdan","Affifudin",
        "Afflu","Afitu","Aghogo","Agudjir","Agustinus",
        "Agustis","Agustyen","Ahab","Ahad","Ahar",
        "Ahiyate","Ahlaro","Ahnary","Ahudora","Ahver",
        "Aihery","Ailerbitu","Ailerkora","Ainoli","Aipassa",
        "Airory","Aitonam","Akasian","Akbar","Akel",
        "Akerina","Akhir","Akiaar","Akiary","Akihary",
        "Akipu","Aklafin","Akohillo","Akollo","Akse",
        "Aktalora","Akyuwen","Al","Al Chatib","Alain",
        "Alakaman","Alamon","Alaslan","Alatubir","Alberthus",
        "Albram","Aldama","Alexander","Alfanay","Alfaris",
        "Alfons","Alicaris","Aliputty","Alkatiri","Alkoteri",
        "Allo","Ally","Aloon","Alopy","Aloumoly",
        "Alputila","Altin","Alvarisi","Alviaro","Alwen",
        "Alwer","Alwy","Bachmid","Bachta","Baco",
        "Bacory","Badelwair","Badmas","Baersady","Bager",
        "Bahasoan","Bain","Bairatnissa","Bairo","Bakarbessy",
        "Bakhwereez","Bakker","Bakridi","Ballan","Ballo",
        "Bally","Balryan","Balsala","Balseran","Balthazar",
        "Balvid","Bamatrao","Bandahera","Banyal","Baora",
        "Baragain","Baransano","Barao","Barek","Barendz",
        "Bareto","Barfeny","Barger","Barkeij","Barlola",
        "Barloy","Barmella","Barnabas","Barons","Baros",
        "Barry","Bartolomeus","Bämfer","Caarsten","Caian",
        "Callahan","Calvari","Camerling","Cao","Capobianco",
        "Carelsz","Carliano","Carmiago","Carolus","Castera",
        "Castillo","Castro","Cecene","Ceda","Chadiman",
        "Chakenota","Chatib","Cheiongers","Chello","Chera",
        "Chevais","Chostantinus","Chrisaldo","Christabel","Christen",
        "Christiaan","Christo","Christoffel","Cuana","Cupoano",
        "Curaçao","Dadiara","Dagang","Dahoklory","Dally",
        "Damava","Dandel","Dando","Daniel","Daniels",
        "Darany","Darato","Dario","Darisera","Darkay",
        "Darmau","Darsantor","Dasfordate","Dasletty","Dasmasela",
        "Dasola","Dates","Datty","Dauole","David",
        "Davidz","Dawan","Day","Dayan","Dayera",
        "Ealpis","Edberth","Edward","Effelewn","Effroean",
        "Efluar","Efraim","Egberth","Eideul","Eirumkuy",
        "Eiwury","Ekram","El","El-Betan","Elake",
        "Elanor","Elath","Elaury","Eleujaan","Eleuwarin",
        "Elewarin","Elfarin","Elier","Eliesen","Elkel",
        "Elle","Ellias","Elmas","Elminero","Elsiba",
        "Elsoin","Elsunan","Elte","Eluwart","Elwarin",
        "Fader","Fadersair","Fador","Faifet","Falaici",
        "Falauf","Falera","Falermury","Falesco","Falikres",
        "Fallen","Famas","Famney","Fanbrene","Fangohoy",
        "Fanlay","Fanumbi","Faraknimella","Farly","Farneubun",
        "Farsin","Fasanlaw","Fasse","Fatbinan","Fatfora",
        "Fatlalona","Fatlira","Fatrua","Fatsey","Fatubun",
        "Fauth","Febby","Febesal","Felara","Felay",
        "Feldbrugge","Felndity","Fendjalang","Fenes","Feninlambir",
        "Fenlop","Fenyapwain","Feoh","Fer","Ferdinandus",
        "Ferlin","Fernandez","Fernando","Fernayan","Ferreira",
        "Fesanrey","Fifaona","Gabian","Gabriel","Gaflomi",
        "Gafrin","Gahetto","Gahinsa","Gaite","Gaitian",
        "Gamar","Gamgenora","Ganay","Ganobal","Ganor",
        "Ganza","Garbim","Gardjalay","Gardjey","Garedja",
        "Garera","Garium","Garlay","Garlora","Garpenassy",
        "Garsiana","Garsina","Gasa","Gasko","Gaspar",
        "Gasper","Gaspersz","Gassam","Gathal","Gato",
        "Gelagoy","Gelfara","Genno","George","Geraldi",
        "Geras","Geresi","Gerrits","Geslauw","Ghosaloi",
        "Gigengack","Habel","Habibu","Hadler","Hahijary",
        "Hahuly","Hahury","Haikutty","Hair","Hakamuly",
        "Hakapaä","Halamury","Halapiry","Halattu","Halawane",
        "Halawet","Halirat","Haliwela","Hallatu","Hallauw",
        "Halos","Haltere","Haluly","Haluna","Hong",
        "Honorsian","Hoor","Hoppus","Horaszon","Hordembun",
        "Horeyaam","Horhoruw","Horosio","Horsael","Horsair",
        "Horst","Horts","Horu","Hosea","Host",
        "Hotjum","Huath","Huibers","Huik","Huily",
        "Huka","Hukom","Hüffner","Ibkar","Icona",
        "Ihalauw","Ilella","Ilely","Ilery","Imasuly",
        "Imea","Imkorle","Imlabla","Immink","Imoliana",
        "Imsula","Imuly","Inanosa","Intopiana","Ipaenem",
        "Ipol","Irapanussa","Iraratu","Iriley","Irkey",
        "Irloy","Irmuply","Isaac","Iscandario","Ischa",
        "Ishak","Iskiwar","Ismael","Isran","Jacob",
        "Jacobs","Jacobus","Jadera","Jaflaun","Jaftoran",
        "Jahya","Jallo","Jalmav","Jamangun","Jambormias",
        "Jamco","Jamrewav","Jamsaref","Jan","Jansay",
        "Jansen","Janser","Janwarin","Jaolath","Japanjatty",
        "Jasso","Jeflely","Jekriel","Jellira","Jempormase",
        "Jempormiasse","Jennia","Jeremias","Jerfatin","Jermias",
        "Kaary","Kabalessy","Kabilaha","Kabrahan","Kadmaerubun",
        "Kadtabal","Kafroly","Kahaela","Kahyoru","Kaibobo",
        "Kaidél","Kaihatu","Kaihena","Kailey","Kaillem",
        "Kailola","Kailolo","Kailuhu","Kaimahrela","Kainama",
        "Kaipatty","Kaisupy","Kaiterlomin","Kaitjily","Kaitjlapatay",
        "Kajihi","Kakay","Kakerissa","Kakiailatu","Kakiay",
        "Kakihena","Kwarmona","Labalen","Labery","Labobar",
        "Labok","Ladisary","Lafina","Lafuur","Lagraduay",
        "Laguhi","Lahale","Lahallo","Laian","Laicerewy",
        "Laidillona","Laikyer","Lailossa","Lailro","Laimeheriwa",
        "Laimena","Laimera","Laimesian","Laimuslo","Lainata",
        "Lainsamputty","Laisina","Laisouw","Laitera","Laiterkuhy",
        "Laitety","Laitjatamu","Laitupa","Lakavin","Lakawael",
        "Lakburlawal","Lakburlawar","Lakes","Lakfo","Lakotany",
        "Laäle","Machmara","Macora","Macsurella","Madelis",
        "Madethen","Madrach","Madubun","Madura","Maelissa",
        "Maerissa","Mafinanik","Maghyn","Magista","Magistroy",
        "Magoher","Mahakena","Mahali","Mahaly","Mahoklory",
        "Mahu","Mahubessy","Mahudin","Mahulauw","Mahulete",
        "Mahupale","Mahwil","Maici","Maifor","Maigoda",
        "Maiheuw","Maihoram","Maik","Mailera","Mailissa",
        "Mailoa","Mailopuw","Mailuhu","Maimena","Mainake",
        "Mainaky","Mainasse","Mainasy","Maintor","Maipau",
        "Mairera","Mairuhu","Maitale","Maitha","Maitimu",
        "Maituni","Makahinda","Makalaypessy","Makalew","Makapuan",
        "Makarawe","Makasenda","Makatey","Makatita","Makeralo",
        "Makewe","Makooy","Malagwar","Malaihollo","Malaka",
        "Malakauseya","Malaluhon","Malawat","Malawau","Male",
        "Maleas","Malesi","Malinder","Malioy","Malirafin",
        "Malirmasele","Malkus","Malloly","Mallur","Maloas",
        "Maloka","Maloky","Malonsilly","Mamaga","Mamisa",
        "Manaha","Manahera","Manait","Manakane","Manay",
        "Mancino","Mandalise","Manderos","Mandessy","Mandry",
        "Manduapessy","Mangar","Mangera","Mangidano","Manginsela",
        "Manila","Manilet","Manina","Manintamahu","Manipa",
        "Manjaruni","Matusea","Maäda’el","Maähury","Maäil",
        "Maälette","Maänary","Maäsuly","Maätita","Maätitaputty",
        "Maätitawaer","Maätoke","Maäturwey","Maäwara","Ma’foloi",
        "Mirima","Nafali","Naflery","Nahaklay","Nahakleky",
        "Nahumarury","Nahumarusy","Nahumuri","Nahusona","Nahusuly",
        "Nahuway","Naim","Nalhonam","Nampasnea","Namserna",
        "Namuru","Nanariain","Nanlessy","Nanlohy","Nanulaitta",
        "Nanuru","Nendissa","Obhetan","Octavians","Oefy",
        "Oersepuny","Ofan","Ohello","Ohman","Ohoilean",
        "Ohoiledjaan","Ohoiledwarin","Ohoimar","Ohoiner","Ohoira",
        "Ohoirenan","Ohoitavun","Ohoitenan","Ohoiulun","Ohoiwirin",
        "Ohoiyuf","Ohorella","Paaijs","Paca","Pahar",
        "Paihra","Paija","Pairhy","Paisina","Pakaila",
        "Pakaless","Pakay","Pakkel","Paknianmewan","Pakniany",
        "Palain","Palajo","Palapessy","Palencar","Paliaky",
        "Palias","Palica","Palijama","Palijate","Palipus",
        "Palisoa","Palpia","Palpialy","Pamounda","Panco",
        "Panjaito","Que","Queljoe","Quezon","Rachil",
        "Rada","Radamussa","Radiena","Radjabaycolle","Radjaloa",
        "Radjawane","Radjoelan","Rafael","Rafel","Rafupaira",
        "Ragalomi","Rahabav","Rahabeat","Rahadad","Rahaded",
        "Rahado","Rahael","Rahajan","Rahakbauw","Rahalob",
        "Rahanar","Rahanbiran","Rahankey","Rahanra","Rahansikwer",
        "Rahanten","Rahantoknam","Rahaor","Raha’il","Sabandar",
        "Sabar","Sabonno","Sadrak","Sadsuitubun","Safenussa",
        "Sagena","Sahabudin","Sahalessy","Sahanaya","Sahar",
        "Saämena","Tabalessy","Tabavmolu","Tabelssy","Taberima",
        "Taborat","Tackow","Tahalea","Tahalele","Tahamata",
        "Tahanora","Tahapary","Tahitoe","Tahiya","Tahnopal",
        "Tahoes","Tahor","Taihitu","Taihuttu","Tail",
        "Ubleeuw","Ubra","Ubvan","Udigary","Udinera",
        "Ukru","Uktolseya","Uktosya","Ulahayanan","Ulate",
        "Ulayo","Ulmatty","Ulorlo","Ulter","Uluputty",
        "Umagaf","Umasangadji","Umasugi","Umawaitina","Umhersuny",
        "Valmores","Vanath","Vanon","Waas","Waasar",
        "Waber","Waelaruno","Waemesse","Wagola","Waifly",
        "Wailenzun","Waäel","Wa’atwahan","Xamson","Xaverius",
        "Yaban","Yabar","Yabarmasse","Yafur","Yahawadan",
        "Yakob","Yaky","Yalmav","Yempormase","Zacharias",
        "Zacheus","Zainilessy","da Costa","da Gomez","da Queljoe",
        "da Silva","da Sousa","da law","de Barrito","de Kock",
        "van Afflen","van Amstel","van Belouw","van Bergen","van Bokhove",
    );

    protected static $titleMale = array('Tn.', 'Bung', 'Om');

    protected static $titleFemale = array('Ny.', 'Nn.');

    protected static $prefix = array(
        'SST.','S.Th.I.','S.Th.','S.TI.','S.T.P.','S.T.','S.Sy.','S.Sos.','S.Si.Teol.',
        'S.Si.','S.SI.','S.SArl.','S.S','S.Pt','S.Psi.','S.Psi','S.Pd.','S.P.','S.Mb',
        'S.Kom.','S.Kep.','S.K.M.','S.IP','S.IK.','S.I.Kom.','S.Hut.','S.H.I.','S.H.',
        'S.Farm.','S.E.I.','S.E.','S.Arl.','S.Ag','S.AP','S.AB.','S.AB','S. Sn','Psi.T.',
        'Psi.P','S.Pd.I.'
    );

    protected static $suffix = array(
        'M.M.SI.','MA','M.TI.','M.T.','M.Stat.','M.Sn','M.Si.','M.SI.','M.SArl.','M.Psi.',
        'M.Pd.','M.MPd.','M.M.','M.Kom.','M.Kn.','M.Inf.','M.Hut.','M.Hum.','M.Farm.',
        'M.Cs.','M.Arl.','M.Ak.','M.Ag.','M.AP','M.AB','M.A.R.S.','Ph.D.'
    );

    /**
     * @example 'S.T.'
     */
    public static function prefix()
    {
        return static::randomElement(static::$prefix);
    }

    /**
     * @example 'Ph.D.'
     */
    public static function suffix()
    {
        return static::randomElement(static::$suffix);
    }
}
