daysUntilStale: 14
daysUntilClose: 7
exemptLabels:
  - "pinned"
  - "security"
# Label to use when marking an issue as stale
staleLabel: "lifecycle/stale"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed after 1 week if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
