<?php

namespace Faker\Provider\bs_BA;

class Address extends \Faker\Provider\Address
{
    protected static $streets = array(
        "Sagradžije", "Kemala Kapetanovića", "Fra Filipa Lastrića", "Hasana Brkića", "Topal Osman paše", "Behdžeta Mutevelića",
        "Šibenska", "Aleja Lipa", "Kolodvorska", "Trg heroja", "Ložionička", "Kupreška", "Zvornička", "Vilsonovo šetalište",
        "Džavida Haverića", "Ante Fijamenga", "Grbavička", "Hercegovačka", "Porodice Ribar", "Zmaja od Bosne", "Banjalučka",
        "Neretvanska", "Krupska", "Kalesijska", "Paromlinska", "Olovska", "Pavla Lukača", "Džamijska", "Derviša Numića",
        "Hamdije Čemerlića", "Dobojska", "Azize Šaćirbegović", "Šanac", "Triglavska", "Sakiba Nišića", "Bletska", "Zagrebačka",
        "Marka Marulića", "Butmirska", "Malta", "Alojza Benca", "Avde Smajlovića", "Hamida Hadžibegića", "Radnička",
        "Samoborska", "Hrasnička", "Fojnička", "Varaždinska", "Envera Šehovića", "BihaćkaSkopljanska", "Vrbaska",
        "Ferde Hauptmana", "Orlovačka", "Roberta C. Frasurea", "Ivanjska", "Zenička", "Bugojanska", "Novopazarska", "Drinska",
        "Put života", "Saliha Udžvarlića", "Posavska", "Splitska", "Husinjska", "Muhameda Ridžanovića", "Pofalićka", "Blagajska",
        "Albanska", "Teočačka", "Nedima Filipovića", "Orašačka", "Hadži Mustafe Penjave", "Milana Preloga", "Antuna Branka Šimića",
        "Fra Matije Divkovića", "Sprečanska", "Krivajska", "Humska", "Petra Sinana Šaina", "Trnovska", "Ljubljanska", "Goraždanska",
        "Gornjovakufska", "Franje Račkog", "Braće Panjeta", "Malezijsko-bosanskog prijateljstva", "Milinkladska",
        "Trg žrtava Srebrenice", "Dr. Mustafe Denišlića", "Šaćira Sikirića", "Koste Hermana", "Emerika Bluma",
        "Mustajbega Fadilpašića", "Kranjčevićeva", "Visočka", "M. Fadilpašića", "Ljubljaska", "Hamdije Pozderca",
        "Ivana Gorana Kovačića", "Tešanjska", "Franca Lehara", "Petra Kočića", "Ruđera Boškovića", "Travnička", "Vrbanja",
        "Trg BiH", "Franca Lehara", "Gabrielle Moreno Locatelli", "Zahira Panjete", "Fočanska", "Reisa Fehima Spahe - čikma",
        "Abdurrahmana Sirije", "Put Mladih Muslimana", "Kalemova", "Beogradska", "Reisa Fehima Spahe", "Halida Nazečića",
        "Kotromanića", "Trg Karla Paržika", "Borak", "Hercega Stjepana", "Vrbovska", "Gradačačka", "Fra Anđela Zvizdovića",
        "Augusta Brauna", "Isaka Samokovlije", "Nevesinjska", "Trebevićka", "Kralja Tvrtka", "Halida Kajtaza", "Ohridska",
        "Maršala Tita", "Velikokladuška", "Džemala Bijedića", "Terezija", "Velešići", "Safeta Mujića", "Omera Stupca",
        "Cazinska", "Urijan Dedina", "Vojvode Momčila Đujića", "Dolina", "Hamida Dizdara", "Ilije Engela", "Kalmija Baruha",
        "Magribija", "Prijedorska", "Dr. Fetaha Bećirbegovića", "Porodice FohtBana Mateja Ninoslava", "Avde Jabučice",
        "Hum brdo", "Maglajska", "Turhanija", "Brčanska", "Prnjavorska", "Crni vrh", "Pećina", "Hiseta", "Marija Mikulića",
        "Đoke Mazalića", "Vladimira Valtera Perića", "Radenka Abazovića", "Alije Kučukalića", "Nova", "Vojvode Radomira Putnika",
        "Antuna Hangija", "Muhameda ef. Pandže", "Goruša", "Strikova", "Ozrenska", "Odobašina", "Amira Krupalije",
        "Mustafe Behmena", "Tekija", "Vrazova", "Debelo brdo", "Srpskih ratnika", "Jajačka", "Mostarska", "Mali Soukbunar",
        "Tepebašina", "Kraljice Jelene", "Hamze Hume", "Alipašina", "Gorica", "Kenana Demirovića", "Mice Todorović",
        "Jusufa Tanovića", "Nusreta Prohića", "Safeta Isovića", "Dajanli Ibrahim-bega", "Stolačka", "Prusačka", "Ključka",
        "Žrtava fašizma", "Ćamila Avdića", "Avde Hume", "Muhameda HadžijahićaVefika Karabdića", "Reisa Džemaludina Čauševića",
        "Harisa Osmanovića", "Vranjače", "Husrefa Redžića", "Sutjeska", "Glasinačka", "Kemal Begova", "Avde Hodžića",
        "Hasana Kikića", "Danijela Ozme", "Dubrovačka", "Soukbunar", "Musala", "Tuzlanska", "Ćamila Sijarića", "Atife Karalić",
        "Golješnica", "Azize Šaćirbegovića", "Zagrebačka", "Lužansko polje", "Zrinski Frankopana", "Nazifa Hadžovića",
        "Mis Irbina", "Branislava Đurđeva", "Nusreta Šišića Dede", "Podgaj", "Braće Begić", "Nurudina Gackića", "Merhemića trg",
        "Mrakuša", "Njegoševa", "Srđana Aleksića", "Koševo", "La Benevolencija", "Alekse Šantića", "Hakije Kulenovića",
        "Ali bega Firdusa", "Amira Muharemovića", "Trebinjska", "Put za Hum", "Ejuba Ademovića", "Skenderija čikma",
        "Trg djece Sarajeva", "Skenderija", "Fehima ef. Čurčića", "Feriza Tumbula", "Mehmed Bega Kapetanovića Ljubušaka",
        "Bosanskih kraljeva", "Josipa VancašaJosipa Vancaša", "Džidžikovac", "Obala Maka Dizdara", "Obala Kulina bana",
        "Kasima Hadžića", "Mehe Smailagića", "Nusreta Šišića", "Miljevići", "Adila Grebe", "Radićeva", "Bužimska", "Gatačka",
        "Tabašnica", "Zuke Džumhura", "Gazihusrefbegova 30", "Saliha Behmena", "Trampina", "Jadranska", "Milana Tepića",
        "Bulevar Meše Selimovića", "Gabelina", "Rizaha Štetića", "Tina Ujevića", "Remzije Pehlivanovića", "Rafaela Gaona",
        "Osmana Đikića", "Zelengorska / Hambina carina", "Ciglanska", "Hazima Šabanovića", "Cicin han", "Šefika Loje",
        "Šenoina", "Pruščakova", "Nadira Kafedžića", "Čekaluša", "Behaudina Selmanovića", "Safeta Hadžića", "Skenderpašina",
        "Kodžina", "Čobanija", "Asima Čamdžića", "Avde Sumbula", "Dolačka", "Sulje Jahića", "Čekaluša čikma", "Kulovića",
        "Koševska", "Bolnička", "Koševsko brdo", "HimzarinaAlije Isakovića", "Branilaca Sarajeva", "Miloša Mandića",
        "Romana Petrovića", "Pozorišni trg Susan Sontag", "Jovana Raškovića", "Pinje Bajraktara", "Majdanska", "Mejtaš",
        "Mehmeda Spahe", "Ludviga Kube", "Tahtali sokak", "Jukićeva", "Braće Kovačević", "Hasana Bibera", "Dalmatinska",
        "Tahmiščina", "Brajkovac", "Omera Kovača", "Muvedina Ramovića", "Prvomajska", "Dola", "Armaganuša", "Šumarska",
        "Stjepana Tomića", "Kevrin potok", "Otona Župančića", "Žagrići", "Kaptol", "Buka", "Ćemaluša", "Sepetarevac",
        "Provare", "Save Skarića", "Vladimira Preloga", "Esada Midžića", "Nadlipe", "Lipe", "Dženetića čikma", "Ivana Cankara",
        "Vejsila Ćurčića", "Omera Kovača Čikma", "Mjedenica", "Bajrama Zenunija", "Sulejmana ef. Musića", "Gimnazijska",
        "Firuz-begova", "Komatin", "Niže banje", "VišnjikDerebent", "Trg solidarnosti", "Bjelave", "Muhameda Kantardžića",
        "Hadžiabdinica", "Gajev trg", "Petrakijina", "Envera Čolakovića", "Jezero", "Sutorinska", "Abdića", "Nikole Pašića",
        "Abdurahmana Muharemije", "Dr. Irfana Ljubijankića", "Hadži-Hajdareva", "Mehmeda Šakira Kurtćehajića",
        "Gornji Miljevići", "Zatikuša", "Berkuša", "Patriotske lige", "Tandareva", "Trg oslobođenja - Alija Izetbegović",
        "Mehmed-paše Sokolovića", "Džemila Krvavca", "Sarač Ismailova", "Bosanskih banova", "Bratunačka čikma", "Bjelave",
        "Ferida Srnje", "Goloderica", "Nikole Kašikovića", "Šekerova", "Grlica", "Nadmejdan", "Draže Mihajlovića", "Ivanići",
        "Petruše", "Za Beglukom", "Ferhadija", "Trg fra Grge Martića", "Derviš Fevzi Mostarca", "Štrosmajerova", "Geteova",
        "Timočka", "Tijesna", "Hamdije Kreševljakovića", "Sulejmana Pačariza Hodže", "Bratunačka", "Grada Bobovca", "Berkuša mala",
        "Zaima Šarca", "Ćumurija", "Hekim Oglu Alipaše", "Pehlivanuša", "Jankovića čikma", "Tekija čikma", "Muse Ćazima Ćatića",
        "Marcela Šnajdera", "Zelenih beretki", "Jelića", "Josipa Štadlera", "Koturova", "Sime Milutinovića", "Betanija",
        "Trg nezavisnosti", "Mula Mustafe Bašeskije", "Tale Ličanina", "Saliha Hadžihusejnovića Muvekita", "Mujkanovića",
        "Jovana Bijelića", "Hadži-Bešireva", "Hadži-Sulejmanova", "Rasima Turkušića", "Mandžina gornja", "Berkuša velika",
        "Despićeva", "Edhema Mulabdića", "Terzibašina", "Nikole Tesle", "Zije Dizdarevića", "Vladislava Skarića", "Bosanska",
        "Mandžina donja", "Višegradska", "Mehmeda Handžića", "Bostarići", "Asima Ferhatovića", "Šejh-Mehmedova", "Hadžiristića",
        "Ismeta Mujezinovića", "Hasana Sušića", "Potoklinica", "Bana Borića", "Balibegovića", "Brdo džamija", "Mehmeda Hadžića",
        "Jaroslava Černija", "Ejuba Delalića", "Karpuzova", "Ašikovac", "Fikreta Ploče", "Ive Andrića", "Krivoglavci",
        "Hamze Orlovića", "Strmac", "Velika avlija", "Mahmuta Bušatlije", "Čadordžina", "Mudželiti mali", "Gazi Husrevbegova",
        "Dejzina Bikića", "Kujundžiluk", "Namika Burazerovića", "Braće Eškenazi", "Mahmuta Bušatlije čikma", "Ahmeda Muradbegovića",
        "Markovo guvno", "Bistrik donja čikma", "Nikole Tesle", "Papučina", "Adžemovića", "Behar", "Esada Karađovića",
        "Bistrik gornja čikma", "Himze Polovine", "Bistrik basamaci", "Mudželiti veliki", "Jedileri", "Toka", "Austrijski trg",
        "Bjelavica", "Mustafe Pašića", "Hadžidamjanova", "Mustafe Busuladžića", "Golobrdica", "Imamovića", "Bistrik potok",
        "Juraja Najtharta", "Mandrina", "Džeka", "Pastrma", "Todora Švrakića", "Čurčiluk mali", "Esada Karađozovića",
        "Kundurdžiluk", "Jabuka", "Ive Andrića", "Bistrik", "Čurčiluk veliki", "ČizmedžilukKrka", "Kazazi", "Na varoši",
        "Đulagina", "Šipska", "Sarači", "Nusreta Fazlibegovića", "Muhameda Enveri Kadića", "Aščiluk", "Kartal", "Bazardžani",
        "Đulagina čikma", "Karla Batka", "Hrgića", "Novi rezervoar", "Rifata Burdževića", "Usorska", "Jasmina Isanovića - Žutog",
        "Hasiba Brankovića", "Breka čikma", "Hameda Buljubašića", "Hulusina", "Trg ZAVNOBIH-a", "Safeta Pašalića",
        "Bistrik medresa", "Kartal donji", "Glođina", "Trgovke", "Bistrik brijeg", "Abadžiluk", "Konak", "Vuka Karadžića",
        "Boguševac", "Kustin sokak", "Breka", "Husage Čišića", "Karađorđeva", "Halači", "Čemerlina", "Prote Bakovića",
        "Glamočka", "Baščaršija", "Hadž-Ahmeda Kandelije", "Tabaci", "Hendina", "Karađorđeva", "Ive Andrića", "Ekmića čikma",
        "Budakovići", "Obala Isa Bega IsakovićaĆulhan", "Smaila Šikala", "Bakarevića", "Alajbegovića", "Safeta Zajke",
        "Kečina", "Đure Jakšića", "Asafa Serdarevića", "Bravadžiluk mali", "Besarina čikma", "Logavina", "Cara Dušana",
        "Branilaca Šipa", "Gandijeva", "Stanojevići", "Toromanova", "Bjelina čikma", "Cara Lazara", "Sagrdžije", "Cara Lazara",
        "Huremuša", "Ragiba Džinde", "Bravadžiluk Halači", "Ilhamina", "Budžak", "Kazandžiluk", "Sunulah-efendije", "Luledžina",
        "Ragiba Džinde", "Ragiba Džinde", "Stara cesta Jezera", "Isevića sokak", "Begovac", "Halim-hodžina", "Alije Đerzeleza",
        "Kasima Prohića", "Oprkanj", "Tahčića sokak", "Okrugla", "Olimpijska", "Trg Ilidžanske brigade", "Telali",
        "Telirovića", "Nahorevska", "Kovači čikma", "Paje", "Budakovići čikma", "Hrastovi", "Hamida Svrze", "Nerkeza Smailagića",
        "Ulomljenica", "Talirevića", "Bravadžiluk", "Nikolića čikma", "Pjera Križanića", "Obala Pariške komune", "Dugi sokak",
        "Franjevačka", "Aleja Bosne srebrne", "Trg Vilijema Šekspira", "Kovači", "Potok", "Brodac", "Jagodića", "Stefana Nemanje",
        "Patke", "Stefana Nemanje", "Garaplina", "Kračule", "Cvijetna", "Kasima ef. Dobrače", "Bardakčije", "Semira Frašte",
        "Iza bašče", "Sulejmana Omerovića - Cara", "Hrvatin", "Piruša", "Fadil-paše Šerifovića", "Prijepoljčeva", "Avdage Šahinagića",
        "Ispod Budakovića", "Mahmutovac", "Sagrdžije čikma", "Trg Barcelone", "Vitkovac", "Humka", "Petra Tješića",
        "Grada Bakua", "Abdesthana", "Midhat Karić Mitke", "Šeher Čehajina čikma", "Gornja Slatina", "Hasana Kaimije",
        "Turbe", "Vareška", "Ticina", "Trg djece Dobrinje", "Mustaj-pašin Mejdan", "Halilbašića", "KamenicaVrbanjuša",
        "Gornja Breka", "I Sarajevske brigade", "Pirin brijeg", "Mehmeda Mujezinovića", "Hamida Beširovića", "Mihrivode",
        "Hadžikajmakova", "Hafiza Ibrahima Trebinjca", "Alifakovac - Megara", "Očaktanum", "Ilhamija", "Veliki Alifakovac",
        "Nadmlini", "Iza hrida", "Avde Ćuka", "Kninska", "Džinina", "Alifakovac", "Dabrobosanska", "Salke Nazečića",
        "Stara cesta II", "Osmana Krupalije", "Hermana Gmeinera", "Toplik", "Braće Morić", "Nedžada Mušića", "Branka Galeba",
        "Hercina", "Nerkesijina", "Džemala Čelića", "Trg međunarodnog prijateljstva", "Esada Pašalića", "Mlini",
        "Evlije Čelebije", "Halilbašića", "Halilovići", "Maguda", "Spasovdanska", "Žepa", "Medrese", "Ante Babića",
        "Kobilja Glava", "Kriva", "Brdovita", "Arapova", "Skendera Kulenovića", "Trg Sarajevske olimpijade", "Jekovac",
        "Šejh-JujeMejlijina", "Panjina kula", "Ramiza Salčina", "Mišćina", "Ploča", "Babića Bašča", "Dr. Silve Rizvanbegović",
        "Uzdojnice", "Akademika Petra Mandića", "Čeljgovići", "Alije Nametka", "Emila Zole", "Šerina", "Akademika Petra Mandića",
        "Lava Tolstoja", "Grada Kalgarija", "Podcarina", "Širokac", "Dabrobosanska", "Omladinskih radnih brigada",
        "Kiseljačka", "Bentbaša", "Kaukčijina", "Saburina", "Požegina", "Hamdije Kapidžića", "Srebrenička", "Adija Mulabegovića",
        "Teheranski trg", "Hilandarska", "Senada Mandića Dende", "Hasana Sućeske", "Nurije Pozderca", "Srpskih vladara",
        "Hilandarska", "Grdonj", "Kunovska", "Srpskih vladara", "Hadžibajrića", "Veliki Kačanik", "Dizdareva", "Kačanik mali",
        "Adema Buće", "Fadila Jahića Španca", "Arberta Fortisa", "Jusufa Juke Gojaka", "Sumbul česma", "Nova Mahala",
        "Dumača", "NalinaSafvet-bega Bašagića", "Gatačka / Istočno Sarajevo", "Zmaj Jovina", "Gornji Hotonj", "Braće Bričić",
        "Hadžišabanovića", "Nevjestina", "Lukavička cesta", "Hadži-Jamakova", "Kozarevići", "Pod bedemom", "Potur Šahidijina",
        "Bulevar branilaca Dobrinje", "Trg Grada Prato", "Nikole Tešanovića", "Stara cesta", "Bulevar Mimar Sinana",
        "Bijela česma", "Trg kralja Aleksandra", "Donji Kromolj", "Alije Miladina", "Sulejmana Zolja", "Kreštalica",
        "Bijela džamija", "Bakije sokak", "Spasovdanska", "Dobrinjske bolnice", "Hošin brijeg", "Janka Jolovića",
        "Sulejmana Filipovića", "Mraovac", "Banović Strahinje", "Mustafe Kamerića", "Trg Sabora Bosanskog", "Vratnik mejdan",
        "Tabijska", "Vinograd", "Jovana Dučića", "Orahovačka", "Orahov brijeg", "Mustafe Dovadžije", "Sedrenik mali",
        "Strošići", "Heljevac", "Trg Zlatnih ljiljana", "Vahide Maglajlić", "Slatina", "Dol", "Rasima Salčina", "Kromolj",
        "Oslobodilaca Sarajeva", "Aleksandra Puškina", "Grličića brdo", "Džanin sokak", "Vuka Karadžića", "Rejhana Demirdžića",
        "Majevička", "Kalhanski sokak", "Omera Hajama", "Dobrinjska", "Miroslava Krleže", "Kršilovac", "Hendek", "Mehmeda Arapčića",
        "Alije Bejtića", "Hadžimustafina", "Marina Držića", "Vojvode Radomira Putnika", "Trčivode gornje", "Karla Mijića",
        "Ramića sokak", "Musluk česma", "Dolovčić Omera", "Mehmed-agina", "Ramića banja", "Senada Poturka Senčija",
        "Luja Pastera", "Mali studenac", "Briješko brdo", "Mustafe Latifića", "Salke Lagumdžije", "Kralja Stjepana Tomaševića",
        "Aziza Sokolića", "Trčivode donje", "Mačkareva", "Midhata Begića", "Tomino brdo", "Mešino ćoše", "Pogledine",
        "Branka Mikulića", "Vladimira Nazora", "Mirze Bakarana", "Fra Antuna Kneževića", "Prijeka česma", "Trg Miroslava Berjana",
        "Voje Dimitrijevića", "Ispod grada", "Elezova", "Nadežde Petrović", "TilavaSarajevskih ilegalaca", "Nafije Sarajlić",
        "Srednja", "Vase Butozana", "Porčina", "Stupsko brdo", "Dolovi", "Asima Behmena", "Zorana Borovine", "Vrandučka",
        "Rudija Alvađa", "Bećarevo ćoše", "Iza gaja", "18. septembra", "Vasilja Grdžića", "Sedrenik", "Mustajbega Ličkog",
        "Ispod Zmajevca", "Branislava Nušića", "Pavlovica", "Eniza Cocalića", "Hakije Turajlića", "Rogina", "Ćebedžije donje",
        "Carina", "Rudi Čajevac", "Habibe Stočević", "Šukrije Pandže", "Dr Kasima Begića", "Zmajevac", "Braće Mulića",
        "Grabska", "Barice", "Franca Prešerna", "Smiljevići", "Poddžebhana", "Ispod oraha", "Vojvode Đujića",
        "Kasindolskog bataljona", "Rudolfa Rude Tomića", "Streljačka", "Osmana Nakaša", "Sarajevskih solunaca", "Omera Šahića",
        "Akifa Šeremeta", "Ćebedžije gornje", "Osječka", "Obrada Popadića", " Višegradska kapija", "Olivera Ibrahimovića",
        "Brezanska", "Alapi", "Izeta Karšića čikma", "Ugorsko III", "Munira Gavrankapetanovića", "Enisa Srne",
        "Andreja Andrejevića", "Filipa Višnjića", "Fehima Agića - Age", "Reufa Muhića", "Latička", "Republike Bugarske",
        "Meše Selimovića", "Put za vrh Trebevića", "Uzeira Sarača", "Sedrenik čikma", "9. januara", "Dariva", "Hajrudina Šabanije",
        "Šefika Dorića", "Izeta Karšića", "Vogošćanska", "Slavka Leovca", "Vojina Komadine", "Petrovići", "Nikole Koljevića",
        "Svetog Nikole", "Ešrefa Kovačevića", "Petra Miloševića", "Petra Miloševića", "Otadžbinska", "Močila", "Jarčedoli",
        "Milutina Najdanovića", "Viteška", "Nikole Šopa", "Ramiza Alića", "Ravnogorska", "Pašino brdo", "Kenana Dubravića",
        "Hifzi Bjelevca", "Besarovića", "Slobodana Janjića", "Sarajevskih gazija", "Briješčanska", "Muje Šejte", "Kurta Schorka",
        "Carice Milice", "Ramiza Gugača", "Hotonj - VogošćaHotonj - Vogošća", "Rašida", "Derokova", "Porodice Šečić",
        "Aleja Bosne Srebrene", "Vitomira Lukića", "Gornji Kromolj", "Kolubarska", "Slavenska", "Zdenka Markulja",
        "Škaljin sokak", "Davorina Popovića", "Stupska", "Nusreta Brkića", "Abdulaha Bošnjaka", "Kasindolskih žrtava",
        "Hotonj II", "Joze Penave", "Ugorsko II", "Hotonj IV", "Mehmedalije Bojića", "Obhodža", "Bačići", "Branilaca Donjeg Kotorca",
        "Poljine", "Mošćanica", "Numan paše Čuprilića", "14. maja 92", "Tuzla Road", "Obhođa", "Joze Penave", "8. marta",
        "Ilidžanska", "Harisa Čampare", "Ulica Tuneli", "Bešlije", "Gazi Mehmed-paše Fidahića", "Dr Atifa Purivatre",
        "Brcko Road", "Dobrinjska", "Sedlanice", "Škaljin sokak (Sokakić)", "Gavrila Principa", "Tuneli", "Friedrich Adolfa",
        "Igmanska", "Dr. Ibrahima Tepića", "Ibre Ćeske", "Bojnička", "Mostar RoadIsmeta Alajbegovića Šerbe", "Franje Kluza",
        "Miloša Crnjanskog", "Zuhdije Kadrića", "Katera", "Salke Terzića", "Hasana Merdžanovića", "Humačka ploča", "Rogatička",
        "13. juni", "Braće Gluhić", "Nikole Kolumbića Šake", "Starine Novaka", "Doboj Road", "Butmitski vrtovi",
        "Butmirski vrtovi", "Porodice Dizdarević", "Porodice Korkut", "I. Alajbegovića Šerbe", "Branka Radičevića",
        "Enesa Bičića", "Rajlovac Road", "Svetosavska", "Samira Radovca", "Sarajevo Road", "Kasindolska", "Hasana Merdžanovića",
        "Bojovića", "Hajduk Veljkova", "Avde Palića", "Ljubija Road", "Ibrahima Pečevije", "Braće Planje", "Jasenje",
        "Aerodromska", "Osmana Asafa Sokolovića", "Plavi put", "Lepenička", "Baruthana", "Izeta Delića", "Mlinska",
        "Sokolska", "Dayton Road", "Brusulje (Hadžijska ravan)", "Brusulje", "Aerodromska", "Lutvije Jukovića Luxa",
        "Porodice Hasagić", "Zaima Imamovića", "Tvornička Pijačna", "Oteška", "Porodice Šehić", "Saliha Žige", "Mladicka",
        "Ograde", "Ibrahima Perviza", "Safeta Krupića", "Omladinska", "Dr Ševale Zildžić-Iblizović", "Sarajevska cesta",
        "Hladivode", "Klek", "Poturovići", "Nova Vogošća", "Krešimira Zelića", "Braće Bešo", "Atifa Čoke", "Izeta Čomora",
        "Put za Borija", "Dr Seida Hukovića", "Ilirska", "Smajla Baftića", "Bajrama Hasanovića", "Ravnogorska", "24. juna",
        "Dr Avde Sućeske", "Butmirskog bataljona", "Saida Hadžića", "Poligonska", "Tvornička", "Braće Aruković", "Zabrđe",
        "Lopate", "21. mart", "Tome Mendeša", "Nedžada Delića", "Rosulje", "Sjenička", "Hadžićka", "Rajlovačka", "Blagovac 2",
        "Riste Anđića", "Braće Helać", "Alije Imamovića", "Jana Doršnera", "Igmanska", "Braće Halać", "Srdjana Kneževića",
        "ZauliceReljevska", "Paljevska", "Partizanskog odreda Zvijezda", "Butmirska cesta", "Jošanička", "Vojvode Živojina Mišića",
        "Hipodrom", "Akifa ef. Biserovića", "Blagovac 3", "Rustem-pašina", "Ahmeda Rizve", "Remzije Veje", "Mehe Porobića",
        "Dobrodo", "Dr Mustafe Pintola", "Akifa ef. Biserovića", "Druge sarajevske brigade", "Spasoja Blagovčanina",
        "Braće Kršo", "Zaima Topčića", "Josipa Slavenskog", "Brusulje (Čavrkov sokak)", "Branilaca vijenca", "Čitlučka",
        "Boška Vujadina", "Faletići", "Gliše Jankovića", "Abdulaha efendije Kantamirije", "Feriza Merzuka", "Vogošćanskih odreda",
        "Harisa Merzića", "Ustanička", "Mala aleja", "Most spasa", "Obala Vojvode Stepe", "Hrasnička cesta", "Mala Aleja",
        "Tome Međe", "Huseina Đoze", "Unska", "Emira Bogunića Čarlija", "Cap. Anamur", "Trešnje", "Donje Biosko",
        "Ibrahima Ljubovica", "Blagovac 4", "Emira Bogunića Čarlija", "Mustafe Ice Voljevice", "Edhema Eke Džubura",
        "Braće BučanTihovici", "Avde Karabegovića", "Srpskih palih boraca", "Blagovac 1", "Osmana ef. Rastodera",
        "Mehmeda Mehmedbašića", "Aladža", "Midhata Hujdura Hujke", "Mliništa", "Banjska", "Put Sarajevo Trebević",
        "1. Bošnjačke brigade", "Gornja Jošanica I", "Bihorska", "Doglodi", "Stevana Sinđelića", "Gornja Jošanica II",
        "Ibrahima Ljubovića", "Sejfulaha Prohe", "Željeznička", "Ivana Brkića", "Kapetana Hajre Mešića", "Jusufa Bublina",
        "Sokolovićkog bataljona", "Put za Barice", "Fadila Hadžića", "Arnaudija", "25. novembar", "Vjekoslava Klaića",
        "Trg rimskih banja", "Medžazi", "Dr. Fuada Muhića", "Franje Vuletića", "Rajlovačka cesta", "Slobodana Mijica",
        "Bare kod Stupa", "Gazi Hasan paše", "Karima Zaimovića", "Ibrahima Hafiza Ridžanovića", "Rahima Čatovića",
        "Petra Sarajevskog", "Dževada Hanjalića", "Marice Uherke", "Ajvaz Dedina", "Bosanskih gazija", "Trg Oteškog bataljona",
        "Bojnička", "Nasihe Kapidžić-Hadžić", "Fridriha Kacera", "B. SokolovićaDragana Kulidžana", "Neumska", "Nihadija",
        "Lužanski put", "Ferhat paše Sokolovića", "Francuske revolucije", "Jahiela Fincija", "Prve samostalne brigade",
        "Barska", "Bjelašnička", "Ahmeda Ljubunčića", "Bajre Kaljanca", "Džananova", "Gorana Čišića", "Spomenik", "12. mart",
        "Samira Ćatovića Kobre", "Sestara Elčić", "12. mart", "Hamze Čelenke", "IV Viteške brigade", "Josipa Pančića",
        "Ahmed-paše Hercegovića", "Zavidovićka", "Šemsudina Sarajlića", "Umihane Čuvidine", "Seada Sinanovića", "Vinka Šamarlića",
        "Vidovdanska", "Fejze Softe", "Krste Hegedušića", "Krivoglavci", "Miloša Obilića", "Radića potok", "Nahorevo",
        "Vojnički vrt", "Teroviča", "Začardak", "Velika aleja", "Ramiza Jašara", "4. avgusta", "Uglješe Uzelca", "Karla Malya",
        "Seada Bublina", "Blažujski drum", "Dobroševićka", "Solunska", "Zabosnice", "Sastavci", "Čolakovića kula", "Zeleni put",
        "Kremeš", "M18", "Brodska", "Podigmanska", "Gornje Biosko", "Vreoca", "Lužansko polje", "Tjepovački put", "Put Famosa",
        "Jasike", "Vreoca", "Srđana Kneževića", "Hreša", "Konaci", "Šehitluci", "Suvada Đulimana", "Trg branilaca Hrasnice",
        "Kobiljak", "Mirsada Foče", "Izeta Mušića", "Derviš-paše Bajezidagića", "Gaj", "Ejuba Sarajkića", "6. aprila",
        "Lasički drum", "Reisa ef. Hadžiomerovića", "Lasičke megare", "Generala Izeta Nanića", "Emira Šabanije", "Školska",
        "Karamusići", "Bjelugovićka", "Bašića sokak", "Ahmeda Bošnjaka", "Kovačev kamen", "Ćamila Marića", "Muniba Avdića",
        "Igmanskih bataljona", "Sabita Užičanina", "Tinjak", "Stojčevac", "Zije Krajine", "Himze Mekića", "Kerima Džafića",
        "Večerica", "Dr. Halid-bega Hrasnice", "Crnih labudova", "Bunica", "15. maj", "Jablanička", "Kolibe", "Uzunovića sokak",
        "Ribnjača", "Put spasa", "Stari drum", "Tukovi", "Stari harem", "Vrelo", "Braće Toković", "Kulenvakufska",
        "Rate Dugonjića", "Tvrdica", "Glavogodina", "Ali-efendije Lokvančića", "Ruževik", "Semizova kula", "Ahatovićka",
        "Mejdan", "Osječki put", "Osik", "Begluk", "Devet šehida", "Bratunačka cesta", "Pandurica", "Drage Filipovića",
        "Čauš", "Botulje", "Hendekuša", "Gornji Osijek", "Igmanska cesta", "Gaj brdo", "Mihaljevska", "Butilska", "Pašića put",
        "Blažuj", "Doljanska", "Mali Kiseljak", "Sarajevska rijeka", "Slana bara", "Šehidska", "Ranovačka", "Bosanski ljiljan",
        "Lukavica--Pale", "Kamenolom", "Kamenolom", "Mekote", "Kamenolom", "Mali Kiseljak", "Djevojačka vodaVlakovo", "Njemanica",
        "Vlakovo", "Put za Igman", "Perići", "Mostarsko raskršće", "Mostarsko raskršće", "Stara pruga", "Binježevo", "Binježevo",
        "Kakrinjski put", "Donji Hadžići", "Rakovička cesta", "Garovci", "Garovci", "Žunovnica", "Igmanska", "Rakovička cesta",
        "Zenički potok", "Anđelka Lažetića", "Veliko polje", "Hadželi", "Hadželi", "126. Ilijaške brigade", "Anđelka Lažetića",
        "Moševićka", "Babin Do", "Zovik", "Poljice", "Olimpijska - Jahorina", "Olimpijska", "Dujmovići", "Čaršijska",
        "Brnjaci", "Dr. Džananovića", "Kadije Uvjesa", "Naselje Luke", "Banjska", "Josipa bana Jelačića", "Polje Višnica",
        "Lukomir", "Branilaca", "Alije Izetbegovića", "311. Lahke brigade", "Trbića polje", "Bosanska", "Donje polje",
        "Banjska", "Trbića polje", "VragoloviBranitelja domovine", "Nikole Šubića Zrinjskog", "Kralja Petra", "Petra Kočića",
        "Petra Kočića", "Cara Dušana", "Zaima Imamovića", "Vitkovići", "Prve zeničke brigade", "Trg Alije Izetbegovića",
        "Crkvice", "Tišina", "Mejdandžik", "Maršala Tita", "Muhameda Seida Serdarevića", "Dr. Safvet-bega Bašagića",
        "Trg Bosne i Hercegovine", "Travnička cesta", "Bosanska", "Tina Ujevića", "Silvija Strahimira Kranjčevića",
        "Boljkovac", "Potoci", "Branilaca grada", "Odvode", "Topčić Polje", "Gazi Husrev-begova", "Dr. Pinkasa Bandta",
        "Maršala Tita", "35. divizije", "Stjepana Radića", "Ulica Prva", "Zagrebačka", "Prva ulica", "Željeznička",
        "Druga ulica", "Bosanska", "Aleja konzula", "Ortiješ", "Kalibunar", "Ive Adnrića", "Ušće", "Kardinala Stepinca",
        "Alekse Šantića", "Braće Fejića", "Kresina", "Dubrovačka", "Kralja Tomislava", "Nikole Šubića Zrinskog", "Konak",
        "Trg hrvatskih velikana", "Kneza Domagoja", "Muje Pašiča", "Put za Opine", "Hajduka Andrije Simića", "Konjusi",
        "Žrtava genocida u Srebrenici", "Lukavačkih brigada", "Patrioske lige", "Trg slobode", "Blagaj", "Kulina bana",
        "Milivoja Mičića", "Maršala Tita", "Kovačuša", "Sultan Ahmedova", "Wagnerova", "Nugle II", "Mije Keroševića Guje",
        "Bulevar II korpusa Armije BiH", "307. motorizovane brigade", "Mehmedalije Maka Dizdara", "Muharema Fizovića Fiska",
        "ZAVNOBIH-a", "Alekse Šantića", "Univerzitetska", "Turalibegova", "Kazan Mahala", "Pozorišna", "Franjevačka",
        "Miška Jovanovića", "Ismeta Mujezinovića", "Muhameda Hevaije Uskufija", "Mihajla i Živka Crnogorčevića", "2. oktobra",
        "Trnovac", "Tržni centar", "Armije RBiH", "Šišava", "Nova Travnička", "Trg žrtava Domovinskog rata", "Kralja Tomislava",
        "Braće Pobrić", "Titova", "111. gračaničke brigade", "Husejnovići", "Trg kralja Tomislava", "Gojka Šuška",
        "Fra Didaka Buntića", "Andrije ŠimićaVinac", "Fra Petra Bakule", "Nikole Pašića", "Svetog Save", "Hilandarska",
        "Pop Ljubina", "Alije Izetbegovića", "Abulaha Kovačevića", "Vražići", "Fra Antuna Kneževića", "A.B. Bušića",
        "Zagrebačka", "II zasjedanja AVNOJ-a", "Kraljice Jelene", "Kralja Stjepana Tomaševića", "Mile", "Nenavište",
        "16. muslimanske brigade", "Husein Kapetana Gradaščevića", "Hazna", "Muderisa Ibrahimbegovića", "Mladena Maglova",
        "Trg mladih", "Banjalučka", "Bulevar mira", "Neznanih junaka", "Ante Starčevića", "Titova", "Safvet-bega Bašagića",
        "Osma ulica", "Teodora Kolokotronisa", "Trg Krajine", "Ramići Ind. Zona", "Akademika Jovana Raškovića", "Vase Pelagića",
        "Bihaćka", "502. Viteške brigade", "5. korpusa", "Bosanska", "Darivalaca krvi", "Srebreničkog genocida",
        "Viteške brigade", "Hasana Mujezinovića", "Nurije Pozderca", "Indire Pjanić", "Generala Izeta Nanića"
    );

    protected static $streetNameFormats = array(
        '{{street}}',
    );

    protected static $streetAddressFormats = array(
        '{{streetName}} {{buildingNumber}}',
    );

    protected static $addressFormats = array(
        '{{streetAddress}}, {{postcode}} {{city}}',
    );

    protected static $cityFormats = array(
        '{{cityName}}',
    );

    protected static $postcode = array('#####');

    /**
     * @link https://bs.wikipedia.org/wiki/Spisak_gradova_i_op%C4%87ina_u_Bosni_i_Hercegovini
     */
    protected static $cityNames = array(
        "Sarajevo", "Banovići", "Bihać", "Bosanska Krupa", "Bosanski Petrovac", "Bosansko Grahovo", "Breza", "Bugojno", "Busovača",
        "Bužim", "Cazin", "Doboj Istok", "Doboj Jug", "Dobretići", "Domaljevac-Šamac", "Donji Vakuf", "Drvar", "Fojnica", "Foča-Ustikolina",
        "Glamoč", "Goražde", "Gornji Vakuf-Uskoplje", "Gradačac", "Gračanica", "Grude", "Hadžići", "Ilijaš", "Jablanica", "Jajce",
        "Kakanj", "Kalesija", "Kiseljak", "Kladanj", "Ključ", "Konjic", "Kreševo", "Kupres", "Livno", "Ljubuški", "Lukavac", "Maglaj",
        "Mostar", "Neum", "Novi Travnik", "Odžak", "Olovo", "Orašje", "Posušje", "Prozor", "Ravno", "Sanski Most", "Sapna", "Srebrenik",
        "Stolac", "Teočak", "Tešanj", "Tomislavgrad", "Travnik", "Tuzla", "Usora", "Vareš", "Velika Kladuša", "Visoko", "Vitez", "Vogošća",
        "Zavidovići", "Zenica", "Čelić", "Čitluk", "Žepče", "Živinice", "Željezno Polje", "Šipovo", "Šekovići", "Šamac", "Čelinac",
        "Čapljina", "Čajniče", "Zvornik", "Vlasenica", "Višegrad", "Ugljevik", "Trebinje", "Trnovo", "Teslić", "Srebrenica", "Srbac",
        "Sokolac", "Rudo", "Rogatica", "Prnjavor", "Prijedor", "Petrovo", "Pelagićevo", "Pale", "Oštra Luka", "Osmaci", "Novo Goražde",
        "Bosanski Novi", "Nevesinje", "Mrkonjić Grad", "Modriča", "Milići", "Lopare", "Ljubinje", "Laktaši", "Kozarska Dubica",
        "Kotor Varoš", "Kostajnica", "Kneževo", "Kalinovik", "Jezero", "Istočno Sarajevo", "Istočni Stari Grad", "Istočni Mostar",
        "Istočni Drvar", "Istočna Ilidža", "Han Pijesak", "Gradiška", "Gacko", "Foča", "Donji Žabar", "Derventa", "Brčko", "Brod",
        "Bratunac", "Bijeljina", "Bileća", "Berkovići", "Banja Luka"
    );

    /**
     * @link https://github.com/umpirsky/country-list/blob/master/data/bs_BA/country.php
     */
    protected static $country = array(
        "Afganistan", "Alandska Ostrva", "Albanija", "Alžir", "Američka Samoa", "Andora", "Angola", "Angvila", "Antarktika",
        "Antigva i Barbuda", "Argentina", "Aruba", "Australija", "Austrija", "Azerbejdžan", "Bahami", "Bahrein", "Bangladeš",
        "Barbados", "Belgija", "Belize", "Benin", "Bermuda", "Bjelorusija", "Bocvana", "Bolivija", "Bosna i Hercegovina",
        "Božićna Ostrva", "Brazil", "Britanska Djevičanska Ostrva", "Britanska Territorija u Indijskom Okeanu", "Brunej",
        "Bugarska", "Burkina Faso", "Burundi", "Butan", "Centralnoafrička Republika", "Crna Gora", "Čad", "Češka", "Čile",
        "Danska", "Demokratska Republika Kongo", "Dijego Garsija", "Djevičanska Ostrva SAD", "Dominika", "Dominikanska Republika",
        "Džersi", "Džibuti", "Egipat", "Ekvador", "Ekvatorijalna Gvineja", "Eritreja", "Estonija", "Etiopija", "Farska Ostrva",
        "Fidži", "Filipini", "Finska", "Folklandska Ostrva", "Francuska", "Francuska Gvajana", "Francuska Polinezija",
        "Francuske Južne Teritorije", "Gabon", "Gambija", "Gana", "Gernzi", "Gibraltar", "Grčka", "Grenada", "Grenland",
        "Gruzija", "Guam", "Gvadelupe", "Gvajana", "Gvatemala", "Gvineja", "Gvineja-Bisao", "Haiti", "Holandija", "Honduras",
        "Hong Kong (S. A. R. Kina)", "Hrvatska", "Indija", "Indonezija", "Irak", "Iran", "Irska", "Island", "Italija",
        "Izrael", "Jamajka", "Japan", "Jemen", "Jermenija", "Jordan", "Južna Džordžija i Južna Sendvič Ostrva", "Južna Koreja",
        "Južni Sudan", "Južnoafrička Republika", "Kajmanska Ostrva", "Kambodža", "Kamerun", "Kanada", "Kanarska ostrva",
        "Kape Verde", "Karipska Holandija", "Katar", "Kazahstan", "Kenija", "Kina", "Kipar", "Kirgizstan", "Kiribati",
        "Kokos (Keling) Ostrva", "Kolumbija", "Komorska Ostrva", "Kongo", "Kosovo", "Kostarika", "Kuba", "Kukova Ostrva",
        "Kurasao", "Kuvajt", "Laos", "Lesoto", "Letonija", "Liban", "Liberija", "Libija", "Lihtenštajn", "Litvanija",
        "Luksemburg", "Madagaskar", "Mađarska", "Majote", "Makao (S. A. R. Kina)", "Makedonija", "Malavi", "Maldivi",
        "Malezija", "Mali", "Malta", "Manja Udaljena Ostrva SAD", "Maroko", "Maršalska Ostrva", "Martinik", "Mauricius",
        "Mauritanija", "Meksiko", "Mijanmar", "Mikronezija", "Moldavija", "Monako", "Mongolija", "Monserat", "Mozambik",
        "Namibija", "Nauru", "Nepal", "Niger", "Nigerija", "Nikaragva", "Niue", "Norfolk Ostrvo", "Norveška", "Nova Kaledonija",
        "Novi Zeland", "Njemačka", "Obala Slonovače", "Oman", "Ostrvo Asension", "Ostrvo Man", "Pakistan", "Palau", "Palestinska Teritorija",
        "Panama", "Papua Nova Gvineja", "Paragvaj", "Peru", "Pitkern", "Poljska", "Porto Riko", "Portugal", "Rejunion",
        "Ruanda", "Rumunija", "Rusija", "Salvador", "Samoa", "San Marino", "Sao Tome i Principe", "Saudijska Arabija",
        "Sejšeli", "Sen Pjer i Mikelon", "Senegal", "Sent Kits i Nevis", "Sent Lucija", "Sent Vinsent i Grenadini",
        "Seuta i Melilja", "Sijera Leone", "Singapur", "Sint Marten", "Sirija", "Sjedinjene Američke Države", "Sjeverna Koreja",
        "Sjeverna Marijanska Ostrva", "Slovačka", "Slovenija", "Solomonska Ostrva", "Somalija", "Srbija", "Sudan", "Surinam",
        "Sv. Bartolomej", "Sv. Martin", "Svalbard i Janmajen Ostrva", "Svazilend", "Sveta Helena", "Španija", "Šri Lanka",
        "Švedska", "Švicarska", "Tadžikistan", "Tajland", "Tajvan", "Tanzanija", "Timor Leste", "Togo", "Tokelau", "Tonga",
        "Trinidad i Tobago", "Tristan da Kunja", "Tunis", "Turkmenistan", "Turks i Kajkos Ostrva", "Turska", "Tuvalu", "Uganda",
        "Ujedinjeni Arapski Emirati", "Ukrajina", "Urugvaj", "Uzbekistan", "Valis i Futuna Ostrva", "Vanuatu", "Vatikan",
        "Velika Britanija", "Venecuela", "Vijetnam", "Zambija", "Zapadna Sahara", "Zimbabve"
    );

    public static function street()
    {
        return static::randomElement(static::$streets);
    }

    public function cityName()
    {
        return static::randomElement(static::$cityNames);
    }
}
