<?php

namespace Faker\Provider\en_GH;

class Address extends \Faker\Provider\Address
{
    private static $cities = array(
        "Goaso",
        "Hwidiem",
        "Kenyasi",
        "Kukuom",
        "Abrepo Junction",
        "Abuakwa",
        "Adum",
        "Afrancho",
        "Agogo",
        "Agona",
        "Ahodwo",
        "Airport",
        "Akumadan",
        "Amakom",
        "Aputuogya",
        "Asafo",
        "Ash-Town",
        "Asokore Mampong",
        "Asokwa",
        "Asuofia",
        "Atonsu",
        "Ayeduasi",
        "Ayigya",
        "Bantama",
        "Barekese",
        "Bekwai",
        "Boadi",
        "Bomso",
        "Breman",
        "Brewery",
        "Buoho",
        "Buokrom Estate",
        "Daban",
        "Dakwadwom",
        "Deduako",
        "Denyame",
        "Effiduase",
        "Ejisu",
        "Ejura",
        "Emina",
        "Esreso",
        "Fawode",
        "Gyinyasi",
        "Jachie Pramso",
        "Kaasi",
        "KNUST",
        "Kodie",
        "Komfo Anokye",
        "Konongo",
        "Kotei",
        "Krofrom",
        "Kumasi",
        "Maakro",
        "Mampong",
        "Mankranso",
        "Manso Nkwanta",
        "Nkawie",
        "North Suntreso",
        "Nyinahin",
        "Obuasi",
        "Oforikrom",
        "Pankrono",
        "Santasi",
        "Sokoban",
        "South Suntreso",
        "Suame",
        "Tafo",
        "Takwa-Maakro",
        "Tanoso",
        "Tepa",
        "TUC",
        "Banda Ahenkro",
        "Brekum",
        "Dormaa Ahenkro",
        "New Drobo",
        "Nsawkaw",
        "Sampa",
        "Sunyani",
        "Atebubu",
        "Buipe",
        "Jema",
        "Kintampo",
        "Kwame Danso",
        "Nkoranza",
        "Prang",
        "Techiman",
        "Wenchi",
        "Yeji",
        "Agona Swedru",
        "Amanfrom",
        "Anomabu",
        "Apam",
        "Bawjiase",
        "Breman Asikuma",
        "Budumburam",
        "Cape Coast",
        "Domeabra",
        "Elmina",
        "Foso",
        "Kasoa Ofaakor",
        "Kasoa Zongo",
        "Liberia Camp",
        "Mankessim",
        "Millennium City",
        "Mumford",
        "Nyakrom",
        "Nyananor",
        "Nyanyano",
        "Oduponkpehe",
        "Opeikuma",
        "Pentecost Seminary",
        "Saltpond",
        "Winneba",
        "Abetifi",
        "Abompe",
        "Aburi",
        "Adeiso",
        "Adjeiikrom",
        "Adukrom",
        "Ahwerease",
        "Akim Oda",
        "Akim Swedru",
        "Akosombo",
        "Akropong",
        "Akwatia",
        "Akyem Hemang",
        "Amanokrom",
        "Apirede",
        "Asamankese",
        "Asesewa",
        "Atimpoku",
        "Ayiensu",
        "Begoro",
        "Bepoase",
        "Bisibom",
        "Bososo",
        "Brekusu",
        "Coaltar",
        "Dawu",
        "Dedesoworako",
        "Donkorkrom",
        "Dwenase",
        "Gyankama",
        "Juaso",
        "Kade",
        "Kibi",
        "Kitase",
        "Koforidua",
        "Kwabeng",
        "Mamfe",
        "Mampong",
        "Mpraeso",
        "New Abirem",
        "Nkawkaw",
        "Nsawam",
        "Nsutam",
        "Obooho",
        "Obosomase",
        "Odumase Krobo",
        "Ofoase",
        "Osino",
        "Peduase",
        "Saaman",
        "Somanya",
        "Summer",
        "Suhum",
        "Tease",
        "Tutu",
        "Abelemkpe",
        "Ablekuma",
        "Abokobi",
        "Abossey Okai",
        "Accra Newtown",
        "Achimota",
        "Adabraka",
        "Adenta",
        "Afienya",
        "Agbogba",
        "Airport",
        "Amasaman",
        "Ashiaman",
        "Ashongman",
        "Aslyum Down",
        "Baatsona - Spintex",
        "Bortianor",
        "Cantonment",
        "Dansoman",
        "Darkuman",
        "Dawhenya",
        "Dodowa",
        "Dome",
        "Dzorwulu",
        "East Legon",
        "Gbawe",
        "Haatso",
        "James Town",
        "Kanda",
        "Kaneshie",
        "Kasoa",
        "Kissieman",
        "Kokrobite",
        "Korle Bu",
        "Kpone",
        "Kwabenya",
        "Kwashieman",
        "Labadi",
        "Labone",
        "Lapaz",
        "Lartebiokorshie",
        "Lashibi",
        "Legon",
        "Madina",
        "Makola",
        "Mallam",
        "McCarthy Hill",
        "Michel Camp",
        "Nima",
        "Nungua",
        "Oblogo Mallam",
        "Odoponkpehe",
        "Odorkor",
        "Osu",
        "Oyarifa",
        "Patang",
        "Prampram",
        "Ridge",
        "Roman Ridge",
        "Sakumono",
        "Santa Maria",
        "Sowutuom",
        "Taifa",
        "Tema",
        "Tema New Town",
        "Tesano",
        "Teshie",
        "Tetegu",
        "Tieman",
        "Tudu",
        "Weija",
        "Westhills",
        "Chinderi",
        "Jasikan",
        "Kadjebi",
        "Kete Krachi",
        "Kpassa",
        "Nkonya",
        "Bole",
        "Buipe",
        "Damango",
        "Salaga",
        "Sawla",
        "Tolon",
        "Bawku",
        "Bolgatanga",
        "Bongo",
        "Navrongo",
        "Paga",
        "Tongo",
        "Funsi",
        "Gwollu",
        "Issa",
        "Jirapa",
        "Kaleo",
        "Lambussie",
        "Lawra",
        "Nadowli",
        "Nandom",
        "Tumu",
        "Wa",
        "Wechiau",
        "Adaklu Waya",
        "Adidome",
        "Aflao",
        "Akatsi",
        "Ave Dakpa",
        "Ho.",
        "Hohoe",
        "Keta",
        "Kpando",
        "Kpetoe",
        "Kpeve",
        "Sogakope",
        "Abase",
        "Aboso",
        "Adiawoso",
        "Adiembra",
        "Adwowa",
        "Agona Nkwanta",
        "Agufo",
        "Ahonozo",
        "Akatachi",
        "Alabokazo",
        "Anaji",
        "Apowa",
        "Apremodo",
        "Asankragua",
        "Awukyere",
        "Axim",
        "Beahu",
        "Bogoso",
        "Busua",
        "Daboase",
        "Dadwen",
        "Diabene",
        "Dixcove",
        "East Tanokrom",
        "Effiakuma",
        "Eikwe",
        "Elubo",
        "Essiama",
        "Essikado",
        "Essipong",
        "Ewusiejo",
        "Fijai",
        "Funko",
        "Half Assini",
        "Hotopo",
        "Inchaban",
        "kansaworado",
        "Kejabil",
        "Kojokrom",
        "Kwawkrom",
        "Kweikuma",
        "kwesimintsim",
        "Manso",
        "Miemia",
        "Mpintsin",
        "New Akwidaa",
        "New Amanfu",
        "New Takoradi",
        "Ngyiresia",
        "Nkroful",
        "Nsein",
        "Ntankoful",
        "Nzulezo",
        "Old Akwidaa",
        "Prestea",
        "Princess Town",
        "Samreboi",
        "Sekondi",
        "Shama",
        "Takoradi",
        "Tarkwa",
        "Tikobo No.1",
        "Tikobo No.2",
        "West Tanokrom",
        "Windy Ridge",
        "Akontombra",
        "Bibiani",
        "Dadieso",
        "Enchi",
        "Juaboso",
        "Sewhi Anhwiaso"
    );

    protected static $country = array(
        'Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica (the territory South of 60 deg S)', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
        'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island (Bouvetoya)', 'Brazil', 'British Indian Ocean Territory (Chagos Archipelago)', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
        'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo', 'Congo', 'Cook Islands', 'Costa Rica', 'Cote d\'Ivoire', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
        'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
        'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia',
        'Faroe Islands', 'Falkland Islands (Malvinas)', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'French Southern Territories',
        'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana',
        'Haiti', 'Heard Island and McDonald Islands', 'Holy See (Vatican City State)', 'Honduras', 'Hong Kong', 'Hungary',
        'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy',
        'Jamaica', 'Japan', 'Jersey', 'Jordan',
        'Kazakhstan', 'Kenya', 'Kiribati', 'Korea', 'Korea', 'Kuwait', 'Kyrgyz Republic',
        'Lao People\'s Democratic Republic', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libyan Arab Jamahiriya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
        'Macao', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
        'Namibia', 'Nauru', 'Nepal', 'Netherlands Antilles', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Norway',
        'Oman',
        'Pakistan', 'Palau', 'Palestinian Territories', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands', 'Poland', 'Portugal', 'Puerto Rico',
        'Qatar',
        'Reunion', 'Romania', 'Russian Federation', 'Rwanda',
        'Saint Barthelemy', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia (Slovak Republic)', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Svalbard & Jan Mayen Islands', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
        'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
        'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'United States Minor Outlying Islands', 'United States Virgin Islands', 'Uruguay', 'Uzbekistan',
        'Vanuatu', 'Venezuela', 'Vietnam',
        'Wallis and Futuna', 'Western Sahara',
        'Yemen',
        'Zambia', 'Zimbabwe'
    );

    private static $regions = array(
        'Ashanti',
        'Brong Ahafo',
        'Bono East',
        'Ahafo',
        'Central',
        'Eastern',
        'Greater Accra',
        'Northern',
        'Savannah',
        'North East',
        'Upper East',
        'Upper West',
        'Volta',
        'Oti',
        'Western',
        'Western North'
    );

    /**
     * Randomly returns a Ghanaian state or county.
     *
     * @return string
     */
    public function city()
    {
        return static::randomElement(static::$cities);
    }

    /**
     * Randomly returns a Ghanaian region.
     *
     * @return string
     */
    public static function region()
    {
        return static::randomElement(static::$regions);
    }
}
