<?php

namespace Faker\Provider\lt_LT;

class Lorem extends \Faker\Provider\Lorem
{
    /**
     * @link https://lt.wiktionary.org/wiki/S%C4%85ra%C5%A1as:Da%C5%BEniausi_lietuvi%C5%A1ki_%C5%BEod%C5%BEiai
     */
    protected static $wordList = array(
        'ir', 'jis', 'būti', 'tas', 'į', 'kad', 'aš', 'kuris', 'su', 'šis', 'galėti', 'o', 'iš', 'kaip', 'darbas', 'ar',
        'kitas', 'turėti', 'visas', 'žmogus', 'Lietuva', 'kas', 'vienas', 'tik', 'savo', 'nuo', 'toks', 'bet', 'ne',
        'apie', 'jau', 'labai', 'metai', 'dar', 'daug', 'tu', 'už', 'bei', 'arba', 'laikas', 'kai', 'taip', 'pats',
        'reikėti', 'per', 'po', 'nebūti', 'čia', 'dėl', 'prie', 'tačiau', 'didelis', 'sistema', 'gamyba', 'įmonė',
        'pirmas', 'nes', 'vieta', 'žemė', 'norėti', 'naujas', 'dabar', 'jei', 'koks', 'žinoti', 'pagal',
        'įstatymas', 'vaikas', 'todėl', 'net', 'iki', 'gyvenimas', 'narys', 'du', 'pirmininkas', 'svarbus', 'ant',
        'grupė', 'Tomas', 'kiekvienas', 'dalis', 'atlikti', 'seimas', 'diena', 'tai', 'sakyti', 'valstybė', 'duomuo',
        'gerai', 'prieš', 'kur', 'negalėti', 'dažnai', 'jeigu', 'pasaulis', 'niekas', 'sudaryti', 'taip pat', 'šalis',
        'klausimas', 'geras', 'nei', 'nustatyti', 'be', 'metas', 'savęs', 'viskas', 'pradėti', 'procesas', 'tada',
        'kartas', 'kiek', 'priimti', 'gauti', 'veikla', 'ūkis', 'vanduo', 'įvairus', 'dirbti', 'gal', 'Vilnius',
        'pagrindinis', 'pateikti', 'pavyzdys', 'imti', 'skirti', 'informacija', 'lietuvis', 'ligonis', 'tarp', 'ranka',
        'tapti', 'dievas', 'bendras', 'vyriausybė', 'priemonė', 'kalbėti', 'miestas', 'žodis', 'projektas',
        'respublika', 'kalba', 'daryti', 'Benas', 'kultūra', 'sąlyga', 'padėti', 'mažas', 'pasakyti', 'antras',
        'aukštas', 'visai', 'naudoti', 'Europa', 'gyventi', 'nors', 'mano', 'atrodyti', 'vėl', 'matyti', 'jog',
        'medžiaga', 'gerbti', 'būdas', 'senas', 'Kaunas', 'manyti', 'valdymas', 'ten', 'tyrimas', 'neturėti', 'mokslas',
        'sprendimas', 'šitas', 'keli', 'darbuotojas', 'operacija', 'priklausyti', 'knyga', 'vadinti', 'laikyti', 'ypač',
        'suprasti', 'problema', 'tikslas', 'asmuo', 'forma', 'galva', 'sunkus', 'atvejis', 'metodas', 'skyrius',
        'daugelis', 'eiti', 'leisti', 'moteris', 'straipsnis', 'padaryti', 'likti', 'toli', 'akis', 'tikrai', 'ne tik',
        'vyras', 'istorija', 'liga', 'organizacija', 'trys', 'tam tikras', 'dalykas', 'Vokietija', 'vėlai', 'pusė',
        'mėnuo', 'kartu', 'struktūra', 'centras', 'veikti', 'gaminys', 'teisė', 'juk', 'numatyti', 'taigi', 'kai kuris',
        'tas pats', 'vadovas', 'lygis', 'joks', 'turtas', 'galimybė', 'objektas', 'rinka', 'beveik', 'siekti',
        'rezultatas', 'visiškai', 'tauta', 'technologija', 'pagrindas', 'ministerija', 'sritis', 'šlaitas', 'bet ir',
        'greitai', 'šeima', 'dokumentas', 'mažai', 'tvarka', 'siūlyti', 'atsirasti', 'tiek', 'ryšys', 'mokykla',
        'tekti', 'socialinis', 'atskiras', 'kokybė', 'komitetas', 'pradžia', 'santykis', 'norma', 'rašyti', 'programa',
        'mokestis', 'ekonominis', 'skaičius', 'vykti', 'mintis', 'vis', 'jėga', 'reikalas', 'vardas', 'bankas',
        'širdis', 'lyg', 'poreikis', 'kontrolė', 'kartais', 'techninis', 'kelias', 'pasiekti', 'rasti', 'vakarai',
        'sukurti', 'fondas', 'kraštas', 'organizavimas', 'nurodyti', 'pritarti', 'abu', 'reikalingas', 'palikti',
        'priežastis', 'amžius', 'prašom', 'kūnas', 'be to', 'paprastai', 'funkcija', 'uoliena', 'paskutinis',
        'įrengimas', 'namai', 'principas', 'kolega', 'balsas', 'baigti', 'grįžti', 'kurti', 'užsienis',
        'ateiti', 'šiandien', 'litas', 'latvis', 'gamta', 'rajonas', 'pinigas', 'ponas', 'baltas',
        'kodėl', 'teikti', 'nuomonė', 'panašus', 'tikras', 'ilgas', 'atitikti', 'prašyti', 'taikyti', 'didis',
        'dėmesys', 'praeiti', 'vis dėlto', 'elementas', 'vaidmuo', 'pas', 'teigti', 'aiškus', 'pro', 'linija',
        'registras', 'tiesa', 'duoti', 'ministras', 'štai', 'dėl to', 'reikalavimas', 'koja', 'negu', 'spręsti',
        'pasirodyti', 'tėvas', 'bažnyčia', 'situacija', 'vokietis', 'darbininkas', 'tikti', 'anksti', 'laukti',
        'kaimas', 'prekė', 'informacinis', 'produkcija', 'nutarimas', 'tarnyba', 'valstybinis', 'jūra', 'minėti',
        'tarsi', 'laisvė', 'pakeisti', 'planas', 'veiksmas', 'dalyvauti', 'gyventojas', 'visuomenė', 'pardavimas',
        'durys', 'pataisa', 'nežinoti', 'paskui', 'veidas', 'kol', 'savas', 'prasmė', 'sutikti', 'pabaiga', 'ieškoti',
        'bendrovė', 'organizuoti', 'detalė', 'kadangi', 'siena', 'valanda', 'žiūrėti', 'susyti', 'rytai',
        'įvertinti', 'kas nors', 'pramonė', 'suteikti', 'vos', 'mokėti', 'vartotojas', 'kilti', 'rodyti', 'tavo',
        'konkretus', 'vykdyti', 'parengti', 'karas', 'teritorija', 'na', 'rytas', 'specialus', 'tipas', 'šaltinis',
        'jausmas', 'autorius', 'jaunas', 'medicina', 'firma', 'ilgai', 'gana', 'pastaras', 'pavadinimas', 'įrankis',
        'lėšos', 'atsakyti', 'ačiū', 'remontas', 'privalėti', 'savaitė', 'išeiti', 'kaina', 'tad', 'dydis', 'keletas',
        'papildyti', 'universitetas', 'gydytojas', 'parodyti', 'prasidėti', 'prezidentas', 'miškas', 'analizė', 'estas',
        'punktas', 'visada', 'galas', 'kitoks', 'mirtis', 'ligoninė', 'tėvai', 'JAV', 'daiktas', 'nereikėti', 'laisvas',
        'stengtis', 'išskirti', 'sąjunga', 'trečias', 'kada', 'kažkas', 'kelti', 'oras', 'Rusija', 'meilė', 'politinis',
        'požiūris', 'bazė', 'savivaldybė', 'teismas', 'vakaras', 'balsuoti', 'reikšti', 'šiaurė', 'būdingas',
        'sveikata', 'taryba', 'veiksnys', 'šviesa', 'gaminti', 'patvirtinti', 'išlaidos', 'vadovauti', 'įstaiga',
        'įtaka', 'užduotis', 'vadintis', 'valdžia', 'asmenybė', 'medis', 'institucija', 'kraujas', 'uždavinys',
        'vertinti', 'apskaičiuoti', 'vidus', 'mokslinis', 'statyba', 'sukelti', 'nuošliauža', 'paprastas', 'reikšmė',
        'apsauga', 'automobilis', 'mirti', 'sūnus', 'aplinka', 'naktis', 'pastebėti', 'tirti', 'galbūt', 'lemti',
        'vartoti', 'Klaipėda', 'atstovas', 'daina', 'mašina', 'planavimas', 'matyt', 'tikėtis', 'žuvis',
        'menas', 'padėtis', 'specialistas', 'pasirinkti', 'variantas', 'kuo', 'artimas', 'dvasia', 'literatūra',
        'pagalba', 'remti', 'idėja', 'vien', 'etapas', 'keturi', 'reikalauti', 'biudžetas', 'kūrinys', 'plotas',
        'saulė', 'laukas', 'skirtingas', 'komanda', 'įranga', 'noras', 'sąvoka', 'blogis', 'cechas',
        'nedidelis', 'rūšis', 'schema', 'Baltija', 'po to', 'trukmė', 'vaistas', 'fizinis', 'iš tikrųjų',
        'personalas', 'ekonomika', 'elgesys', 'kompiuteris', 'spalva', 'vyresnis', 'vidinis', 'staiga', 'stovėti',
        'teorija', 'atsižvelgti', 'kambarys', 'nenorėti', 'įvykis', 'apibūdinti', 'sirgti', 'tinklas', 'zona', 'įvykti',
        'partija', 'srautas', 'brolis', 'jausti', 'paruošti', 'gražus', 'riba', 'Amerika', 'juodas', 'padalinys',
        'panaudoti', 'savybė', 'vienetas', 'ateitis', 'dauguma', 'irgi', 'prisiminti', 'technika', 'apskaita',
        'transportas', 'valia', 'skaityti', 'suvokti', 'kitaip', 'gatvė', 'pripažinti', 'tūkstantis', 'žinios',
        'kryptis', 'langas', 'nė', 'oda', 'protas', 'kalnas', 'paslauga', 'institutas', 'motina', 'sutartis', 'vadyba',
        'vertė', 'bandyti', 'sunkiai', 'keisti', 'namas', 'rodiklis', 'valdyti', 'apimtis', 'pagaliau', 'salė',
        'direktorius', 'kontroliuoti', 'tarti', 'turinys', 'esmė', 'laikotarpis', 'parašyti', 'pobūdis', 'mm',
        'organizacinis', 'tiesiog', 'rengti', 'tarptautinis', 'blogas', 'plačiai', 'stiprus', 'kiekis', 'kultas',
        'energija', 'galvoti', 'gamybinis', 'maistas', 'minutė', 'nuolat', 'patirti', 'stebėti', 'sudėtingas',
        'Latvija', 'akmuo', 'laidas', 'įdomus', 'aktas', 'pagaminti', 'žmona', 'lengvai', 'išleisti', 'išorinis',
        'koks nors', 'produktas', 'verslas', 'gyvas', 'muzika', 'paukštis', 'paviršius', 'būklė', 'netgi',
        'pamatyti', 'patekti', 'priminti', 'taisyklė', 'ciklas', 'stalas', 'apskritai', 'atsakomybė', 'draugija',
        'būtent', 'gerokai', 'konfliktas', 'kūryba', 'komisija', 'upė', 'parduoti', 'pastatas', 'svarstyti',
        'Lenkija', 'paaiškinti', 'sujungti', 'žaisti', 'mokytojas', 'pažinti', 'apimti', 'aprašyti', 'deja', 'pienas',
        'rungtynės', 'saugoti', 'Estija', 'nagrinėti', 'patalpa', 'rašytojas', 'tvirtinti', 'ekspertizė', 'vienintelis',
        'beje', 'policija', 'aptarnavimas', 'atvykti', 'judesys', 'ženklas', 'byla', 'liepa', 'parama', 'užmokestis',
        'vasara', 'aiškiai', 'priėmimas', 'sėdėti', 'bendravimas', 'girdėti', 'reiškinys', 'tuomet', 'Ryga', 'lova',
        'poetas', 'posėdis', 'sesuo', 'vertinimas', 'vertybė', 'pažymėti', 'procentas', 'bent', 'grandinė', 'pasak',
        'perduoti', 'pirkti', 'pranešėjas', 'užimti', 'Vytautas', 'platus', 'seniai', 'atsisakyti', 'mokslininkas',
        'motyvas', 'studentas', 'tirpalas', 'draudimas', 'filosofija', 'kūrimas', 'pietūs', 'tiksliai', 'įgyvendinti',
        'asmeninis', 'baigtis', 'gimti', 'paskirti', 'politika', 'projektavimas', 'atsakymas', 'finansai', 'kol kas',
        'modelis', 'palyginti', 'patenkinti', 'skirtis', 'stambus', 'tam', 'tarpusavis', 'draugas', 'istorinis',
        'iškilti', 'pakeitimas', 'procedūra', 'aptarti', 'ekspertas', 'naudojimas', 'lentelė', 'lizdas', 'nematyti',
        'išduoti', 'pajamos', 'surinkti', 'kova', 'vaizdas', 'doleris', 'klasė', 'pagalbinis', 'pasiūlymas', 'požymis',
        'prekyba', 'tamsus', 'augti', 'gi', 'nuostata', 'paskelbti', 'siela', 'skatinti', 'išvada', 'partneris',
        'trumpas', 'bendrauti', 'lengvas', 'pirštas', 'tiktai', 'įrašyti', 'brangus', 'pasaulinis', 'pilis', 'spauda',
        'susidaryti', 'tautinis', 'tikėti', 'Jonas', 'kompleksas', 'skausmas', 'kapitalas', 'paimti', 'pavadinti',
        'svetimas', 'šiek tiek', 'gydymas', 'organas', 'raštas', 'tikėjimas', 'Aleksandras', 'grafikas', 'lapas',
        'pora', 'turbūt', 'anas', 'drabužis', 'gyvulys', 'išlikti', 'laikytis', 'numeris', 'sandėlis', 'svečias',
        'tekstas', 'šalia', 'aiškinti', 'dalyvis', 'vis tiek', 'kelionė', 'žingsnis', 'pasidaryti', 'poveikis',
        'raudonas', 'šaka', 'šaltas', 'ūkininkas', 'individualus', 'lietuviškas', 'm', 'mama', 'pereiti', 'srovinis',
        'tradicija', 'Maskva', 'dirbinys', 'pareigūnas', 'susipažinti', 'vidutinis', 'žaidimas', 'egzistuoti',
        'išmokti', 'klaida', 'paskola', 'penki', 'prarasti', 'priskirti', 'rimtas', 'temperatūra', 'terminas',
        'vidurys', 'Baltarusija', 'mėginti', 'nutarti', 'pagalvoti', 'pakankamai', 'praktika', 'suomis', 'užtikrinti',
        'vienetinis', 'atviras', 'didžiulis', 'pasiūlyti', 'rūmai', 'žvilgsnis', 'laivas', 'palaikyti', 'pirminis',
        'prietaisas', 'tamsa', 'dešimtmetis', 'kaip tik', 'patirtis', 'vakar', 'Prancūzija', 'baimė', 'dvasinis',
        'elektra', 'para', 'sudėtis', 'šitaip', 'iš esmės', 'kaltė', 'kampas', 'kreiptis', 'liaudis', 'mokytis',
        'nors ir', 'paskirtis', 'pastatyti', 'pelnas', 'remtis', 'staklės', 'sveikas', 'sąrašas', 'apskritis',
        'kompiuterizuoti', 'pasikeisti', 'sandara', 'stadija', 'vasaris', 'eilėraštis', 'interesas', 'kažkoks',
        'kunigaikštis', 'pasakoti', 'skaičiavimas', 'dabartinis', 'daugiausia', 'klubas', 'mokymas', 'pradas',
        'sumažėti', 'taškas', 'visa tai', 'švietimas', 'žiema', 'imtis', 'išreikšti', 'mėgti', 'padidėti', 'pamažu',
        'smulkus', 'šlapimas', 'akcinis', 'praeitis', 'įsivaizduoti', 'dangus', 'elgtis', 'indas', 'kilmė',
        'koeficientas', 'raida', 'sportas', 'vilkas', 'Sokratas', 'kodas', 'koncepcija', 'pabrėžti', 'realus',
        'statyti', 'subjektas', 'taurė', 'tema', 'atsarga', 'ir', 'į', 'kad', 'yra', 'su', 'iš', 'o', 'ir', 'tai',
        'buvo', 'kaip', 'ar', 'savo', 'nuo', 'jis', 'bet', 'ne', 'apie', 'jų', 'tik', 'jo', 'jau', 'dar', 'darbo',
        'Lietuvos', 'gali', 'būti', 'aš', 'už', 'bei', 'arba', 'kai', 'po', 'labai', 'turi', 'jos', 'dėl', 'čia', 'per',
        'taip', 'prie', 'tačiau', 'kas', 'jie', 'galima', 'ji', 'reikia', 'nes', 'metų', 'dabar', 'mūsų',
        'jei', 'gamybos', 'pagal', 'todėl', 'net', 'iki', 'būtų', 'mes', 'ant', 'daug', 'ką', 'tai', 'nėra', 'bus',
        'jį', 'kur', 'jeigu', 'ir', 'daugiau', 'pirmininkas', 'taip pat', 'nei', 'be', 'seimo', 'tada', 'kiek',
        'gal', 'prieš', 'žmogus', 'ar', 'kurie', 'žemės', 'metu', 'pats', 'tarp', 'jam', 'to', 'kuris', 'žmogaus',
        'Tomas', 'kitų', 'man', 'įmonės', 'laiko', 'visi', 'tas', 'ją', 'visai', 'žmonių', 'mano', 'vėl',
        'juos', 'jog', 'respublikos', 'ūkio', 'kaip', 'ten', 'Lietuvoje', 'gerai', 'tą', 'valstybės', 'sistemos',
        'ypač', 'nors', 'pavyzdžiui', 'kurios', 'šis', 'duomenų', 'šios', 'lietuvių', 'ne tik', 'gyvenimo', 'kuri',
        'metais', 'kartu', 'žmonės', 'valdymo', 'šio', 'tu', 'kartą', 'dažnai', 'juk', 'visą', 'nieko', 'vienas',
        'taigi', 'kurių', 'tuo', 'vėliau', 'beveik', 'Benas', 'du', 'visiškai', 'Vilniaus', 'bet ir', 'darbų',
        'toks', 'šių', 'tiek', 'Europos', 'šį', 'toliau', 'tikrai', 'kultūros', 'Kauno', 'šiuo', 'jūs', 'ši',
        'dalis', 'sistema', 'visų', 'kiti', 'pasaulio', 'tokia', 'viskas', 'kartais', 'priklauso', 'ėmė', 'grupės',
        'lyg', 'labiau', 'nebuvo', 'prašom', 'veiklos', 'vandens', 'dažniausiai', 'darbą', 'be to', 'kitą',
        'vyriausybės', 'įstatymo', 'kurį', 'metus', 'informacijos', 'dieną', 'šiandien',
        'turėjo', 'kodėl', 'jiems', 'vieną', 'negali', 'šie', 'sudaro', 'vis dėlto', 'viską', 'žinoma', 'pas',
        'pro', 'visas', 'turėtų', 'štai', 'laikas', 'dėl to', 'negu', 'atrodo', 'kitas', 'paprastai', 'kurio',
        'atlikti', 'mums', 'tarsi', 'save', 'nariai', 'tų', 'geriau', 'miesto', 'vietos', 'visus', 'tos', 'vakarų',
        'mokslo', 'kol', 'kadangi', 'narys', 'tik', 'laiką', 'o', 'mane', 'niekas', 'vos', 'tavo', 'dvi',
        'vienas', 'šią', 'visa', 'litų', 'gana', 'gerbiamasis', 'jas', 'tapo', 'tau', 'pirmiausia', 'atveju', 'ačiū',
        'kiekvienas', 'na', 'ko', 'Vokietijos', 'būna', 'darbas', 'latvių', 'užsienio', 'rinkos', 'tad', 'visos', 'tie',
        'jūsų', 'nustatyti', 'kokybės', 'uolienų', 'visada', 'mažiau', 'paskui', 'jai', 'JAV', 'daryti', 'kitos', 'mus',
        'kada', 'anksčiau', 'būtina', 'vietą', 'tokių', 'medicinos', 'taip', 'technologijos', 'dievo', 'galėtų',
        'darbuotojų', 'kita', 'rytų', 'sunku', 'svarbu', 'sau', 'pasakyti', 'ta', 'šalių', 'turto', 'viena', 'sako',
        'tvarka', 'šlaito', 'galbūt', 'pati', 'neturi', 'vyriausybė', 'matyt', 'greitai', 'kito', 'vis',
        'istorijos', 'vien', 'vadinasi', 'medžiagų', 'vieną', 'reikėtų', 'sistemą', 'širdies', 'dviejų', 'nori',
        'tokios', 'kitus', 'kurią', 'vaikų', 'vokiečių', 'koks', 'organizavimo',
        'iš tikrųjų', 'po to', 'kuriuos', 'patys', 'šiaurės', 'dirbti', 'gamtos', 'įmonių', 'staiga', 'būdu',
        'informacija', 'šalies', 'skyriaus', 'gyvenimą', 'per', 'produkcijos', 'gerbiamieji', 'kalba', 'irgi',
        'priimti', 'dievas', 'negalima', 'tiesa', 'aišku', 'kitaip', 'registro', 'tokį', 'darbus', 'kuriame',
        'skaičius', 'gauti', 'Baltijos', 'įvairių', 'kalbos', 'amžiaus', 'pramonės', 'priemonių', 'tautos', 'tokie',
        'tokio', 'mokesčių', 'nė', 'operacijos', 'tuos', 'vaikai', 'pradėjo', 'remonto', 'ilgai', 'padaryti',
        'pagaliau', 'galvą', 'manau', 'narių', 'žmogui', 'atrodė', 'mm', 'tiesiog', 'akis', 'kontrolės', 'pradžioje',
        'apsaugos', 'kokia', 'klausimas', 'nuolat', 'sveikatos', 'veikla', 'kitais', 'priemonės', 'komiteto', 'dienos',
        'dienų', 'naujų', 'rodo', 'tampa', 'kartus', 'kūno', 'kalbėti', 'mėnesį', 'pardavimų', 'pasaulyje', 'proceso',
        'netgi', 'įstatymą', 'Klaipėdos', 'gaminių', 'apskritai', 'ministerijos', 'moteris', 'padėti',
        'būtent', 'dalį', 'gerokai', 'pateikti', 'rajono', 'transporto', 'estų', 'padeda', 'visiems', 'Lietuvą',
        'forma', 'gyvenimas', 'ponas', 'deja', 'duomenys', 'įrengimų', 'norėčiau', 'prekių', 'sakė', 'tave', 'viena',
        'šiame', 'abu', 'laiku', 'tris', 'vis', 'beje', 'kurias', 'kurioje', 'organizacijos', 'ekonomikos', 'kolega',
        'tuomet', 'ligonio', 'leidžia', 'bent', 'daugelis', 'ligonis', 'lėšų', 'pasak', 'pinigų', 'šeimos', 'darbai',
        'karo', 'veikia', 'noriu', 'seniai', 'sąlygomis', 'tenka', 'galėjo', 'nereikia', 'turėti', 'kol kas', 'Rusijos',
        'kiekvieno', 'kuo', 'lygio', 'tam', 'įstatymas', 'jums', 'keletą', 'vaikas', 'aiškiai', 'fondo', 'kuo', 'trys',
        'Lietuva', 'meno', 'finansų', 'grupė', 'laisvės', 'savęs', 'sąlygas', 'vyrai', 'kiekvieną', 'klausimą',
        'projektą', 'spręsti', 'esant', 'gi', 'greičiau', 'jame', 'juo', 'kai kurie', 'ministras', 'biudžeto', 'krašto',
        'prieš', 'reiškia', 'tikslas', 'labiausiai', 'pakeisti', 'sudaryti', 'dirba', 'informaciją', 'operacijų',
        'personalo', 'teisės', 'tokią', 'nuomone', 'požiūriu', 'atlieka', 'vyksta', 'šiek tiek', 'pabaigoje', 'vadybos',
        'viso', 'visuomenės', 'dėmesio', 'turbūt', 'vaiko', 'įmonėse', 'Vilniuje', 'dalykas', 'straipsnio', 'žmogų',
        'atsiranda', 'esu', 'gyventojų', 'medžiagos', 'ranka', 'vieta', 'vietų', 'vis tiek', 'kitiems', 'liepos',
        'sunkiai', 'vietoje', 'naudoti', 'struktūros', 'šiuos', 'jūros', 'kokios', 'm', 'planavimo', 'matyti',
        'problema', 'daugelio', 'dauguma', 'procesų', 'tyrimų', 'balsuoti', 'jokių', 'kaimo', 'komitetas',
        'pagrindiniai', 'pakankamai', 'liko', 'paties', 'detalių', 'kontrolė', 'projekto', 'dėmesį', 'mintis', 'nebūtų',
        'vakar', 'žmones', 'dalies', 'jau', 'ligos', 'namų', 'skiriasi', 'veiklą', 'šitaip', 'formos', 'iš esmės',
        'nors ir', 'prašau', 'priemones', 'teisę', 'tyrimo', 'įmonė', 'bažnyčios', 'stalo', 'pagrindinis',
        'sąlygų', 'šito', 'daugiausia', 'visa tai', 'kokie', 'pamažu', 'pasirodė', 'sąlygos', 'didelis', 'dolerių',
        'liaudies', 'lieka', 'naujas', 'procesas', 'rankas', 'tarnybos', 'teko', 'įmonėje', 'šitą', 'žemę', 'energijos',
        'klausimus', 'mirties', 'didelė', 'elektros', 'iš pradžių', 'joje', 'kiekviena', 'kraujo', 'mokyklos', 'naktį',
        'pasaulį', 'skirti', 'tarybos', 'tokiu', 'aptarnavimo', 'atskirų', 'firmos', 'gyventi', 'metai',
        'naujos', 'oro', 'rašė', 'gaminio', 'gyvena', 'normos', 'svarbus', 'tik', 'galime', 'kolegos', 'meilės', 'pusę',
        'struktūra', 'grupių', 'iš karto', 'laikų', 'reikėjo', 'tėvas', 'vadovas', 'atsirado', 'galvos', 'ima',
        'pagrindas', 'pradėti', 'problemų', 'duris', 'durų', 'itin', 'palyginti', 'reikalų', 'statybos', 'universiteto',
        'vasario', 'draudimo', 'ką nors', 'priežastis', 'sąjungos', 'šioje', 'atgal', 'darbininkų', 'darbuotojai',
        'liga', 'ligoninės', 'naują', 'pasiekti', 'plačiai', 'salėje', 'tipo', 'įvertinti', 'atvejais', 'manęs',
        'tautų', 'tinka', 'visuomet', 'dirbo', 'duomenis', 'tiktai', 'asmenybės', 'iki šiol', 'pirmą',
        'vaikus', 'valstybė', 'vieno', 'vietas', 'apskaitos', 'centro', 'nemažai', 'privalo', 'sukurti', 'svarbiausia',
        'verslo', 'įstatymų', 'Vilnius', 'daro', 'linijos', 'norint', 'pietų', 'prekybos', 'rezultatų', 'srityje',
        'turiu', 'valdžios', 'asmens', 'mokėti', 'trukmė', 'lietuviai', 'niekada', 'pieno', 'pritarti',
        'turime', 'švietimo', 'gamyba', 'gyvenime', 'kelis', 'kur kas', 'laikais', 'literatūros', 'regis', 'suomių',
        'trumpai', 'Vokietijoje', 'kovo', 'maisto', 'mažai', 'žinoti', 'balsas', 'kelių', 'knygos', 'prezidentas',
        'savaitę', 'tuo tarpu', 'vardu', 'vidaus', 'vienas', 'pradeda', 'vaidmenį', 'Kaune', 'iš viso', 'link',
        'maždaug', 'mokslų', 'pirmasis', 'reikės', 'ryto', 'analizė', 'centras', 'moterys', 'nežinau', 'projektas',
        'projektavimo', 'buvęs', 'funkcijas', 'istorija', 'iš tiesų', 'jokios', 'ligų', 'priežasčių', 'sienos',
        'vadovai', 'vieno', 'virš', 'Latvijos', 'bendrovės', 'dalykų', 'kažkas', 'lemia', 'ministerija', 'mokesčio',
        'programos', 'ryšių', 'sporto', 'teritorijos', 'tėvai', 'vartotojų', 'vienu', 'Tomo', 'klausimai', 'sprendimo',
        'suprasti', 'vis dar', 'žmonėms', 'Kolosauskas', 'knyga', 'nebus', 'prasidėjo', 'technikos', 'tiesiogiai',
        'užmokesčio', 'Aleksandras', 'atsižvelgiant', 'funkcijos', 'lengviau', 'rasti', 'įtakos', 'atžvilgiu', 'būdavo',
        'kalbą', 'kartų', 'laikyti', 'medžiaga', 'objekto', 'pirmas', 'proto', 'reikalavimus', 'įrankių', 'šalyse',
        'Lietuvai', 'iš anksto', 'kojų', 'norma', 'prasme', 'remiantis', 'siūlo', 'valia', 'šalia', 'šviesos',
        'Amerikos', 'birželio', 'buvau', 'ii', 'netrukus', 'nuošliaužos', 'asmenų', 'lygis', 'pagalbos', 'rankų',
        'saulės', 'sprendimą', 'vanduo', 'šiais', 'dokumentų', 'jėga', 'kitam', 'kuriam', 'organizacijų',
        'problemos', 'tapti', 'valstybių', 'šeima', 'žmona', 'autorius', 'keli', 'mano', 'pasakė', 'straipsnį', 'tam',
        'šiam', 'šias', 'žinau', 'žino', 'galimybę', 'galva', 'jais', 'kas', 'kūrimo', 'namo', 'pavadinimas',
        'policijos', 'skyriuje', 'srities', 'teismo', 'vaistų', 'vandeniu', 'LGS', 'komisare', 'kurti', 'metodus',
        'namuose', 'nelabai', 'nustatyta', 'organizuoti', 'panaudoti', 'paramos', 'partijos', 'priėmimo', 'tiksliai',
        'įtaką', 'jėgos', 'kelias', 'knygų', 'mama', 'mašinų', 'nedaug', 'objektų', 'reikalauja', 'reikalavimai',
        'rezultatus', 'teikia', 'vadinama', 'Estijos', 'baltų', 'banko', 'bendras', 'blogio', 'ciklo', 'lt', 'mat',
        'metodai', 'pobūdžio', 'rankos', 'siekiant', 'žemė', 'būdas', 'galimybes', 'gamyboje', 'jėgų', 'pagrindinių',
        'pirmoji', 'priimtas', 'puikiai', 'rytą', 'trijų', 'Baltarusijos', 'asmuo', 'elgesio', 'knygą', 'kuriems',
        'labdaros', 'ligonį', 'neseniai', 'sistemų', 'tėvų', 'vardas', 'vyrų', 'įvyko', 'šitas', 'darbui', 'diena',
        'dokumentus', 'dviem', 'muzikos', 'mėnesių', 'pagrindo', 'pačiam', 'rusų', 'tulžies', 'vertės', 'įrangos',
        'žodžiai', 'žodžio', 'Europoje', 'bendravimo', 'dainų', 'dalykai', 'elementų', 'kyla', 'organizavimas', 'pusės',
        'savivaldybės', 'siūlau', 'turtą', 'tvarkymo', 'tvarką', 'veiksmų', 'žodžių', 'ieškoti', 'naudojimo',
        'parengti', 'pinigus', 'tavęs', 'vasarą', 'šlapimo', 'direktorius', 'galiu', 'kai kurių'
    );
}
