<?php

namespace Faker\Provider\es_ES;

class Text extends \Faker\Provider\Text
{
    /**
     * {@link} http://www.quijotipsum.com/
     *
     * @var string
     */
    protected static $baseText = <<<'EOT'
En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lantejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de entresemana se honraba con su vellorí de lo más fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años; era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque, por conjeturas verosímiles, se deja entender que se llamaba Quejana. Pero esto importa poco a nuestro cuento; basta que en la narración dél no se salga un punto de la verdad.

Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba ocioso, que eran los más del año, se daba a leer libros de caballerías, con tanta afición y gusto, que olvidó casi de todo punto el ejercicio de la caza, y aun la administración de su hacienda. Y llegó a tanto su curiosidad y desatino en esto, que vendió muchas hanegas de tierra de sembradura para comprar libros de caballerías en que leer, y así, llevó a su casa todos cuantos pudo haber dellos; y de todos, ningunos le parecían tan bien como los que compuso el famoso Feliciano de Silva, porque la claridad de su prosa y aquellas entricadas razones suyas le parecían de perlas, y más cuando llegaba a leer aquellos requiebros y cartas de desafíos, donde en muchas partes hallaba escrito: La razón de la sinrazón que a mi razón se hace, de tal manera mi razón enflaquece, que con razón me quejo de la vuestra fermosura. Y también cuando leía: ...los altos cielos que de vuestra divinidad divinamente con las estrellas os fortifican, y os hacen merecedora del merecimiento que merece la vuestra grandeza.

Con estas razones perdía el pobre caballero el juicio, y desvelábase por entenderlas y desentrañarles el sentido, que no se lo sacara ni las entendiera el mesmo Aristóteles, si resucitara para sólo ello. No estaba muy bien con las heridas que don Belianís daba y recebía, porque se imaginaba que, por grandes maestros que le hubiesen curado, no dejaría de tener el rostro y todo el cuerpo lleno de cicatrices y señales. Pero, con todo, alababa en su autor aquel acabar su libro con la promesa de aquella inacabable aventura, y muchas veces le vino deseo de tomar la pluma y dalle fin al pie de la letra, como allí se promete; y sin duda alguna lo hiciera, y aun saliera con ello, si otros mayores y continuos pensamientos no se lo estorbaran. Tuvo muchas veces competencia con el cura de su lugar -que era hombre docto, graduado en Sigüenza-, sobre cuál había sido mejor caballero: Palmerín de Ingalaterra o Amadís de Gaula; mas maese Nicolás, barbero del mesmo pueblo, decía que ninguno llegaba al Caballero del Febo, y que si alguno se le podía comparar, era don Galaor, hermano de Amadís de Gaula, porque tenía muy acomodada condición para todo; que no era caballero melindroso, ni tan llorón como su hermano, y que en lo de la valentía no le iba en zaga.

En resolución, él se enfrascó tanto en su letura, que se le pasaban las noches leyendo de claro en claro, y los días de turbio en turbio; y así, del poco dormir y del mucho leer, se le secó el celebro, de manera que vino a perder el juicio. Llenósele la fantasía de todo aquello que leía en los libros, así de encantamentos como de pendencias, batallas, desafíos, heridas, requiebros, amores, tormentas y disparates imposibles; y asentósele de tal modo en la imaginación que era verdad toda aquella máquina de aquellas sonadas soñadas invenciones que leía, que para él no había otra historia más cierta en el mundo. Decía él que el Cid Ruy Díaz había sido muy buen caballero, pero que no tenía que ver con el Caballero de la Ardiente Espada, que de sólo un revés había partido por medio dos fieros y descomunales gigantes. Mejor estaba con Bernardo del Carpio, porque en Roncesvalles había muerto a Roldán el encantado, valiéndose de la industria de Hércules, cuando ahogó a Anteo, el hijo de la Tierra, entre los brazos. Decía mucho bien del gigante Morgante, porque, con ser de aquella generación gigantea, que todos son soberbios y descomedidos, él solo era afable y bien criado. Pero, sobre todos, estaba bien con Reinaldos de Montalbán, y más cuando le veía salir de su castillo y robar cuantos topaba, y cuando en allende robó aquel ídolo de Mahoma que era todo de oro, según dice su historia. Diera él, por dar una mano de coces al traidor de Galalón, al ama que tenía, y aun a su sobrina de añadidura.

En efeto, rematado ya su juicio, vino a dar en el más estraño pensamiento que jamás dio loco en el mundo; y fue que le pareció convenible y necesario, así para el aumento de su honra como para el servicio de su república, hacerse caballero andante, y irse por todo el mundo con sus armas y caballo a buscar las aventuras y a ejercitarse en todo aquello que él había leído que los caballeros andantes se ejercitaban, deshaciendo todo género de agravio, y poniéndose en ocasiones y peligros donde, acabándolos, cobrase eterno nombre y fama. Imaginábase el pobre ya coronado por el valor de su brazo, por lo menos, del imperio de Trapisonda; y así, con estos tan agradables pensamientos, llevado del estraño gusto que en ellos sentía, se dio priesa a poner en efeto lo que deseaba.

Y lo primero que hizo fue limpiar unas armas que habían sido de sus bisabuelos, que, tomadas de orín y llenas de moho, luengos siglos había que estaban puestas y olvidadas en un rincón. Limpiólas y aderezólas lo mejor que pudo, pero vio que tenían una gran falta, y era que no tenían celada de encaje, sino morrión simple; mas a esto suplió su industria, porque de cartones hizo un modo de media celada, que, encajada con el morrión, hacían una apariencia de celada entera. Es verdad que para probar si era fuerte y podía estar al riesgo de una cuchillada, sacó su espada y le dio dos golpes, y con el primero y en un punto deshizo lo que había hecho en una semana; y no dejó de parecerle mal la facilidad con que la había hecho pedazos, y, por asegurarse deste peligro, la tornó a hacer de nuevo, poniéndole unas barras de hierro por de dentro, de tal manera que él quedó satisfecho de su fortaleza; y, sin querer hacer nueva experiencia della, la diputó y tuvo por celada finísima de encaje.

Fue luego a ver su rocín, y, aunque tenía más cuartos que un real y más tachas que el caballo de Gonela, que tantum pellis et ossa fuit, le pareció que ni el Bucéfalo de Alejandro ni Babieca el del Cid con él se igualaban. Cuatro días se le pasaron en imaginar qué nombre le pondría; porque, según se decía él a sí mesmo, no era razón que caballo de caballero tan famoso, y tan bueno él por sí, estuviese sin nombre conocido; y ansí, procuraba acomodársele de manera que declarase quién había sido, antes que fuese de caballero andante, y lo que era entonces; pues estaba muy puesto en razón que, mudando su señor estado, mudase él también el nombre, y le cobrase famoso y de estruendo, como convenía a la nueva orden y al nuevo ejercicio que ya profesaba. Y así, después de muchos nombres que formó, borró y quitó, añadió, deshizo y tornó a hacer en su memoria e imaginación, al fin le vino a llamar Rocinante: nombre, a su parecer, alto, sonoro y significativo de lo que había sido cuando fue rocín, antes de lo que ahora era, que era antes y primero de todos los rocines del mundo.

Puesto nombre, y tan a su gusto, a su caballo, quiso ponérsele a sí mismo, y en este pensamiento duró otros ocho días, y al cabo se vino a llamar don Quijote; de donde -como queda dicho- tomaron ocasión los autores desta tan verdadera historia que, sin duda, se debía de llamar Quijada, y no Quesada, como otros quisieron decir. Pero, acordándose que el valeroso Amadís no sólo se había contentado con llamarse Amadís a secas, sino que añadió el nombre de su reino y patria, por Hepila famosa, y se llamó Amadís de Gaula, así quiso, como buen caballero, añadir al suyo el nombre de la suya y llamarse don Quijote de la Mancha, con que, a su parecer, declaraba muy al vivo su linaje y patria, y la honraba con tomar el sobrenombre della.

Limpias, pues, sus armas, hecho del morrión celada, puesto nombre a su rocín y confirmándose a sí mismo, se dio a entender que no le faltaba otra cosa sino buscar una dama de quien enamorarse; porque el caballero andante sin amores era árbol sin hojas y sin fruto y cuerpo sin alma. Decíase él a sí:

ahí con algún gigante, como de ordinario les acontece a los caballeros andantes, y le derribo de un encuentro, o le parto por mitad del cuerpo, o, finalmente, le venzo y le rindo, ¿no será bien tener a quien enviarle presentado y que entre y se hinque de rodillas ante mi dulce señora, y diga con voz humilde y rendido: ''Yo, señora, soy el gigante Caraculiambro, señor de la ínsula Malindrania, a quien venció en singular batalla el jamás como se debe alabado caballero don Quijote de la Mancha, el cual me mandó que me presentase ante vuestra merced, para que la vuestra grandeza disponga de mí a su talante''?

¡Oh, cómo se holgó nuestro buen caballero cuando hubo hecho este discurso, y más cuando halló a quien dar nombre de su dama! Y fue, a lo que se cree, que en un lugar cerca del suyo había una moza labradora de muy buen parecer, de quien él un tiempo anduvo enamorado, aunque, según se entiende, ella jamás lo supo, ni le dio cata dello. Llamábase Aldonza Lorenzo, y a ésta le pareció ser bien darle título de señora de sus pensamientos; y, buscándole nombre que no desdijese mucho del suyo, y que tirase y se encaminase al de princesa y gran señora, vino a llamarla Dulcinea del Toboso, porque era natural del Toboso; nombre, a su parecer, músico y peregrino y significativo, como todos los demás que a él y a sus cosas había puesto.

Hechas, pues, estas prevenciones, no quiso aguardar más tiempo a poner en efeto su pensamiento, apretándole a ello la falta que él pensaba que hacía en el mundo su tardanza, según eran los agravios que pensaba deshacer, tuertos que enderezar, sinrazones que emendar, y abusos que mejorar y deudas que satisfacer. Y así, sin dar parte a persona alguna de su intención, y sin que nadie le viese, una mañana, antes del día, que era uno de los calurosos del mes de julio, se armó de todas sus armas, subió sobre Rocinante, puesta su mal compuesta celada, embrazó su adarga, tomó su lanza, y, por la puerta falsa de un corral, salió al campo con grandísimo contento y alborozo de ver con cuánta facilidad había dado principio a su buen deseo. Mas, apenas se vio en el campo, cuando le asaltó un pensamiento terrible, y tal, que por poco le hiciera dejar la comenzada empresa; y fue que le vino a la memoria que no era armado caballero, y que, conforme a ley de caballería, ni podía ni debía tomar armas con ningún caballero; y, puesto que lo fuera, había de llevar armas blancas, como novel caballero, sin empresa en el escudo, hasta que por su esfuerzo la ganase. Estos pensamientos le hicieron titubear en su propósito; mas, pudiendo más su locura que otra razón alguna, propuso de hacerse armar caballero del primero que topase, a imitación de otros muchos que así lo hicieron, según él había leído en los libros que tal le tenían. En lo de las armas blancas, pensaba limpiarlas de manera, en teniendo lugar, que lo fuesen más que un armiño; y con esto se quietó y prosiguió su camino, sin llevar otro que aquel que su caballo quería, creyendo que en aquello consistía la fuerza de las aventuras.

Verdadera historia de mis famosos hechos, que el sabio que los escribiere no ponga, cuando llegue a contar esta mi primera salidad tan de mañana, desta manera?: «Apenas había el rubicundo Apolo tendido por la faz de la ancha y espaciosa tierra las doradas hebras de sus hermosos cabellos, y apenas los pequeños y pintados pajarillos con sus arpadas lenguas habían saludado con dulce y meliflua armonía la venida de la rosada aurora, que, dejando la blanda cama del celoso marido, por las puertas y balcones del manchego horizonte a los mortales se mostraba, cuando el famoso caballero don Quijote de la Mancha, dejando las ociosas plumas, subió sobre su famoso caballo Rocinante, y comenzó a caminar por el antiguo y conocido campo de Montiel».

Casi todo aquel día caminó sin acontecerle cosa que de contar fuese, de lo cual se desesperaba, porque quisiera topar luego luego con quien hacer experiencia del valor de su fuerte brazo. Autores hay que dicen que la primera aventura que le avino fue la del Puerto Lápice; otros dicen que la de los molinos de viento; pero, lo que yo he podido averiguar en este caso, y lo que he hallado escrito en los Anales de la Mancha, es que él anduvo todo aquel día, y, al anochecer, su rocín y él se hallaron cansados y muertos de hambre; y que, mirando a todas partes por ver si descubriría algún castillo o alguna majada de pastores donde recogerse y adonde pudiese remediar su mucha hambre y necesidad, vio, no lejos del camino por donde iba, una venta, que fue como si viera una estrella que, no a los portales, sino a los alcázares de su redención le encaminaba. Diose priesa a caminar, y llegó a ella a tiempo que anochecía.

Estaban acaso a la puerta dos mujeres mozas, destas que llaman del partido, las cuales iban a Sevilla con unos arrieros que en la venta aquella noche acertaron a hacer jornada; y, como a nuestro aventurero todo cuanto pensaba, veía o imaginaba le parecía ser hecho y pasar al modo de lo que había leído, luego que vio la venta, se le representó que era un castillo con sus cuatro torres y chapiteles de luciente plata, sin faltarle su puente levadiza y honda cava, con todos aquellos adherentes que semejantes castillos se pintan. Fuese llegando a la venta, que a él le parecía castillo, y a poco trecho della detuvo las riendas a Rocinante, esperando que algún enano se pusiese entre las almenas a dar señal con alguna trompeta de que llegaba caballero al castillo. Pero, como vio que se tardaban y que Rocinante se daba priesa por llegar a la caballeriza, se llegó a la puerta de la venta, y vio a las dos destraídas mozas que allí estaban, que a él le parecieron dos hermosas doncellas o dos graciosas damas que delante de la puerta del castillo se estaban solazando. En esto, sucedió acaso que un porquero que andaba recogiendo de unos rastrojos una manada de puercos -que, sin perdón, así se llaman- tocó un cuerno, a cuya señal ellos se recogen, y al instante se le representó a don Quijote lo que deseaba, que era que algún enano hacía señal de su venida; y así, con estraño contento, llegó a la venta y a las damas, las cuales, como vieron venir un hombre de aquella suerte, armado y con lanza y adarga, llenas de miedo, se iban a entrar en la venta; pero don Quijote, coligiendo por su huida su miedo, alzándose la visera de papelón y descubriendo su seco y polvoroso rostro, con gentil talante y voz reposada, les dijo:

Dijo luego al huésped que le tuviese mucho cuidado de su caballo, porque era la mejor pieza que comía pan en el mundo. Miróle el ventero, y no le pareció tan bueno como don Quijote decía, ni aun la mitad; y, acomodándole en la caballeriza, volvió a ver lo que su huésped mandaba, al cual estaban desarmando las doncellas, que ya se habían reconciliado con él; las cuales, aunque le habían quitado el peto y el espaldar, jamás supieron ni pudieron desencajarle la gola, ni quitalle la contrahecha celada, que traía atada con unas cintas verdes, y era menester cortarlas, por no poderse quitar los ñudos; mas él no lo quiso consentir en ninguna manera, y así, se quedó toda aquella noche con la celada puesta, que era la más graciosa y estraña figura que se pudiera pensar; y, al desarmarle, como él se imaginaba que aquellas traídas y llevadas que le desarmaban eran algunas principales señoras y damas de aquel castillo, les dijo con mucho donaire:

El ventero, que, como está dicho, era un poco socarrón y ya tenía algunos barruntos de la falta de juicio de su huésped, acabó de creerlo cuando acabó de oírle semejantes razones, y, por tener qué reír aquella noche, determinó de seguirle el humor; y así, le dijo que andaba muy acertado en lo que deseaba y pedía, y que tal prosupuesto era propio y natural de los caballeros tan principales como él parecía y como su gallarda presencia mostraba; y que él, ansimesmo, en los años de su mocedad, se había dado a aquel honroso ejercicio, andando por diversas partes del mundo buscando sus aventuras, sin que hubiese dejado los Percheles de Málaga, Islas de Riarán, Compás de Sevilla, Azoguejo de Segovia, la Olivera de Valencia, Rondilla de Granada, Playa de Sanlúcar, Potro de Córdoba y las Ventillas de Toledo y otras diversas partes, donde había ejercitado la ligereza de sus pies, sutileza de sus manos, haciendo muchos tuertos, recuestando muchas viudas, deshaciendo algunas doncellas y engañando a algunos pupilos, y, finalmente, dándose a conocer por cuantas audiencias y tribunales hay casi en toda España; y que, a lo último, se había venido a recoger a aquel su castillo, donde vivía con su hacienda y con las ajenas, recogiendo en él a todos los caballeros andantes, de cualquiera calidad y condición que fuesen, sólo por la mucha afición que les tenía y porque partiesen con él de sus haberes, en pago de su buen deseo.

Díjole también que en aquel su castillo no había capilla alguna donde poder velar las armas, porque estaba derribada para hacerla de nuevo; pero que, en caso de necesidad, él sabía que se podían velar dondequiera, y que aquella noche las podría velar en un patio del castillo; que a la mañana, siendo Dios servido, se harían las debidas ceremonias, de manera que él quedase armado caballero, y tan caballero que no pudiese ser más en el mundo.

Preguntóle si traía dineros; respondió don Quijote que no traía blanca, porque él nunca había leído en las historias de los caballeros andantes que ninguno los hubiese traído. A esto dijo el ventero que se engañaba; que, puesto caso que en las historias no se escribía, por haberles parecido a los autores dellas que no era menester escrebir una cosa tan clara y tan necesaria de traerse como eran dineros y camisas limpias, no por eso se había de creer que no los trujeron; y así, tuviese por cierto y averiguado que todos los caballeros andantes, de que tantos libros están llenos y atestados, llevaban bien herradas las bolsas, por lo que pudiese sucederles; y que asimismo llevaban camisas y una arqueta pequeña llena de ungüentos para curar las heridas que recebían, porque no todas veces en los campos y desiertos donde se combatían y salían heridos había quien los curase, si ya no era que tenían algún sabio encantador por amigo, que luego los socorría, trayendo por el aire, en alguna nube, alguna doncella o enano con alguna redoma de agua de tal virtud que, en gustando alguna gota della, luego al punto quedaban sanos de sus llagas y heridas, como si mal alguno hubiesen tenido. Mas que, en tanto que esto no hubiese, tuvieron los pasados caballeros por cosa acertada que sus escuderos fuesen proveídos de dineros y de otras cosas necesarias, como eran hilas y ungüentos para curarse; y, cuando sucedía que los tales caballeros no tenían escuderos, que eran pocas y raras veces, ellos mesmos lo llevaban todo en unas alforjas muy sutiles, que casi no se parecían, a las ancas del caballo, como que era otra cosa de más importancia; porque, no siendo por ocasión semejante, esto de llevar alforjas no fue muy admitido entre los caballeros andantes; y por esto le daba por consejo, pues aún se lo podía mandar como a su ahijado, que tan presto lo había de ser, que no caminase de allí adelante sin dineros y sin las prevenciones referidas, y que vería cuán bien se hallaba con ellas cuando menos se pensase.

Prometióle don Quijote de hacer lo que se le aconsejaba con toda puntualidad; y así, se dio luego orden como velase las armas en un corral grande que a un lado de la venta estaba; y, recogiéndolas don Quijote todas, las puso sobre una pila que junto a un pozo estaba, y, embrazando su adarga, asió de su lanza y con gentil continente se comenzó a pasear delante de la pila; y cuando comenzó el paseo comenzaba a cerrar la noche.

Contó el ventero a todos cuantos estaban en la venta la locura de su huésped, la vela de las armas y la armazón de caballería que esperaba. Admiráronse de tan estraño género de locura y fuéronselo a mirar desde lejos, y vieron que, con sosegado ademán, unas veces se paseaba; otras, arrimado a su lanza, ponía los ojos en las armas, sin quitarlos por un buen espacio dellas. Acabó de cerrar la noche, pero con tanta claridad de la luna, que podía competir con el que se la prestaba, de manera que cuanto el novel caballero hacía era bien visto de todos. Antojósele en esto a uno de los arrieros que estaban en la venta ir a dar agua a su recua, y fue menester quitar las armas de don Quijote, que estaban sobre la pila; el cual, viéndole llegar, en voz alta le dijo:

Y, diciendo estas y otras semejantes razones, soltando la adarga, alzó la lanza a dos manos y dio con ella tan gran golpe al arriero en la cabeza, que le derribó en el suelo, tan maltrecho que, si segundara con otro, no tuviera necesidad de maestro que le curara. Hecho esto, recogió sus armas y tornó a pasearse con el mismo reposo que primero. Desde allí a poco, sin saberse lo que había pasado (porque aún estaba aturdido el arriero), llegó otro con la mesma intención de dar agua a sus mulos; y, llegando a quitar las armas para desembarazar la pila, sin hablar don Quijote palabra y sin pedir favor a nadie, soltó otra vez la adarga y alzó otra vez la lanza, y, sin hacerla pedazos, hizo más de tres la cabeza del segundo arriero, porque se la abrió por cuatro. Al ruido acudió toda la gente de la venta, y entre ellos el ventero. Viendo esto don Quijote, embrazó su adarga, y, puesta mano a su espada, dijo:

Con esto cobró, a su parecer, tanto ánimo, que si le acometieran todos los arrieros del mundo, no volviera el pie atrás. Los compañeros de los heridos, que tales los vieron, comenzaron desde lejos a llover piedras sobre don Quijote, el cual, lo mejor que podía, se reparaba con su adarga, y no se osaba apartar de la pila por no desamparar las armas. El ventero daba voces que le dejasen, porque ya les había dicho como era loco, y que por loco se libraría, aunque los matase a todos. También don Quijote las daba, mayores, llamándolos de alevosos y traidores, y que el señor del castillo era un follón y mal nacido caballero, pues de tal manera consentía que se tratasen los andantes caballeros; y que si él hubiera recebido la orden de caballería, que él le diera a entender su alevosía:

No le parecieron bien al ventero las burlas de su huésped, y determinó abreviar y darle la negra orden de caballería luego, antes que otra desgracia sucediese. Y así, llegándose a él, se desculpó de la insolencia que aquella gente baja con él había usado, sin que él supiese cosa alguna; pero que bien castigados quedaban de su atrevimiento. Díjole como ya le había dicho que en aquel castillo no había capilla, y para lo que restaba de hacer tampoco era necesaria; que todo el toque de quedar armado caballero consistía en la pescozada y en el espaldarazo, según él tenía noticia del ceremonial de la orden, y que aquello en mitad de un campo se podía hacer, y que ya había cumplido con lo que tocaba al velar de las armas, que con solas dos horas de vela se cumplía, cuanto más, que él había estado más de cuatro. Todo se lo creyó don Quijote, y dijo que él estaba allí pronto para obedecerle, y que concluyese con la mayor brevedad que pudiese; porque si fuese otra vez acometido y se viese armado caballero, no pensaba dejar persona viva en el castillo, eceto aquellas que él le mandase, a quien por su respeto dejaría.

Advertido y medroso desto el castellano, trujo luego un libro donde asentaba la paja y cebada que daba a los arrieros, y con un cabo de vela que le traía un muchacho, y con las dos ya dichas doncellas, se vino adonde don Quijote estaba, al cual mandó hincar de rodillas; y, leyendo en su manual, como que decía alguna devota oración, en mitad de la leyenda alzó la mano y diole sobre el cuello un buen golpe, y tras él, con su mesma espada, un gentil espaldazaro, siempre murmurando entre dientes, como que rezaba. Hecho esto, mandó a una de aquellas damas que le ciñese la espada, la cual lo hizo con mucha desenvoltura y discreción, porque no fue menester poca para no reventar de risa a cada punto de las ceremonias; pero las proezas que ya habían visto del novel caballero les tenía la risa a raya.

Don Quijote le preguntó cómo se llamaba, porque él supiese de allí adelante a quién quedaba obligado por la merced recebida; porque pensaba darle alguna parte de la honra que alcanzase por el valor de su brazo. Ella respondió con mucha humildad que se llamaba la Tolosa, y que era hija de un remendón natural de Toledo que vivía a las tendillas de Sancho Bienaya, y que dondequiera que ella estuviese le serviría y le tendría por señor. Don Quijote le replicó que, por su amor, le hiciese merced que de allí adelante se pusiese don y se llamase doña Tolosa. Ella se lo prometió, y la otra le calzó la espuela, con la cual le pasó casi el mismo coloquio que con la de la espada: preguntóle su nombre, y dijo que se llamaba la Molinera, y que era hija de un honrado molinero de Antequera; a la cual también rogó don Quijote que se pusiese don y se llamase doña Molinera, ofreciéndole nuevos servicios y mercedes.

Hechas, pues, de galope y aprisa las hasta allí nunca vistas ceremonias, no vio la hora don Quijote de verse a caballo y salir buscando las aventuras; y, ensillando luego a Rocinante, subió en él, y, abrazando a su huésped, le dijo cosas tan estrañas, agradeciéndole la merced de haberle armado caballero, que no es posible acertar a referirlas. El ventero, por verle ya fuera de la venta, con no menos retóricas, aunque con más breves palabras, respondió a las suyas, y, sin pedirle la costa de la posada, le dejó ir a la buen hora.

La del alba sería cuando don Quijote salió de la venta, tan contento, tan gallardo, tan alborozado por verse ya armado caballero, que el gozo le reventaba por las cinchas del caballo. Mas, viniéndole a la memoria los consejos de su huésped cerca de las prevenciones tan necesarias que había de llevar consigo, especial la de los dineros y camisas, determinó volver a su casa y acomodarse de todo, y de un escudero, haciendo cuenta de recebir a un labrador vecino suyo, que era pobre y con hijos, pero muy a propósito para el oficio escuderil de la caballería. Con este pensamiento guió a Rocinante hacia su aldea, el cual, casi conociendo la querencia, con tanta gana comenzó a caminar, que parecía que no ponía los pies en el suelo.

Y, volviendo las riendas, encaminó a Rocinante hacia donde le pareció que las voces salían. Y, a pocos pasos que entró por el bosque, vio atada una yegua a una encina, y atado en otra a un muchacho, desnudo de medio cuerpo arriba, hasta de edad de quince años, que era el que las voces daba; y no sin causa, porque le estaba dando con una pretina muchos azotes un labrador de buen talle, y cada azote le acompañaba con una reprehensión y consejo. Porque decía:

El labrador bajó la cabeza y, sin responder palabra, desató a su criado, al cual preguntó don Quijote que cuánto le debía su amo. Él dijo que nueve meses, a siete reales cada mes. Hizo la cuenta don Quijote y halló que montaban setenta y tres reales, y díjole al labrador que al momento los desembolsase, si no quería morir por ello. Respondió el medroso villano que para el paso en que estaba y juramento que había hecho -y aún no había jurado nada-, que no eran tantos, porque se le habían de descontar y recebir en cuenta tres pares de zapatos que le había dado y un real de dos sangrías que le habían hecho estando enfermo.

Un mozo de mulas de los que allí venían, que no debía de ser muy bien intencionado, oyendo decir al pobre caído tantas arrogancias, no lo pudo sufrir sin darle la respuesta en las costillas. Y, llegándose a él, tomó la lanza, y, después de haberla hecho pedazos, con uno dellos comenzó a dar a nuestro don Quijote tantos palos que, a despecho y pesar de sus armas, le molió como cibera. Dábanle voces sus amos que no le diese tanto y que le dejase, pero estaba ya el mozo picado y no quiso dejar el juego hasta envidar todo el resto de su cólera; y, acudiendo por los demás trozos de la lanza, los acabó de deshacer sobre el miserable caído, que, con toda aquella tempestad de palos que sobre él vía, no cerraba la boca, amenazando al cielo y a la tierra, y a los malandrines, que tal le parecían.

Cansóse el mozo, y los mercaderes siguieron su camino, llevando qué contar en todo él del pobre apaleado. El cual, después que se vio solo, tornó a probar si podía levantarse; pero si no lo pudo hacer cuando sano y bueno, ¿cómo lo haría molido y casi deshecho? Y aún se tenía por dichoso, pareciéndole que aquélla era propia desgracia de caballeros andantes, y toda la atribuía a la falta de su caballo, y no era posible levantarse, según tenía brumado todo el cuerpo.

Viendo, pues, que, en efeto, no podía menearse, acordó de acogerse a su ordinario remedio, que era pensar en algún paso de sus libros; y trújole su locura a la memoria aquel de Valdovinos y del marqués de Mantua, cuando Carloto le dejó herido en la montiña, historia sabida de los niños, no ignorada de los mozos, celebrada y aun creída de los viejos; y, con todo esto, no más verdadera que los milagros de Mahoma. Ésta, pues, le pareció a él que le venía de molde para el paso en que se hallaba; y así, con muestras de grande sentimiento, se comenzó a volcar por la tierra y a decir con debilitado aliento lo mesmo que dicen decía el herido caballero del bosque:

Y quiso la suerte que, cuando llegó a este verso, acertó a pasar por allí un labrador de su mesmo lugar y vecino suyo, que venía de llevar una carga de trigo al molino; el cual, viendo aquel hombre allí tendido, se llegó a él y le preguntó que quién era y qué mal sentía que tan tristemente se quejaba. Don Quijote creyó, sin duda, que aquél era el marqués de Mantua, su tío; y así, no le respondió otra cosa si no fue proseguir en su romance, donde le daba cuenta de su desgracia y de los amores del hijo del Emperante con su esposa, todo de la mesma manera que el romance lo canta.

Pero él seguía con su romance a cuanto le preguntaba. Viendo esto el buen hombre, lo mejor que pudo le quitó el peto y espaldar, para ver si tenía alguna herida; pero no vio sangre ni señal alguna. Procuró levantarle del suelo, y no con poco trabajo le subió sobre su jumento, por parecer caballería más sosegada. Recogió las armas, hasta las astillas de la lanza, y liólas sobre Rocinante, al cual tomó de la rienda, y del cabestro al asno, y se encaminó hacia su pueblo, bien pensativo de oír los disparates que don Quijote decía; y no menos iba don Quijote, que, de puro molido y quebrantado, no se podía tener sobre el borrico, y de cuando en cuando daba unos suspiros que los ponía en el cielo; de modo que de nuevo obligó a que el labrador le preguntase le dijese qué mal sentía; y no parece sino que el diablo le traía a la memoria los cuentos acomodados a sus sucesos, porque, en aquel punto, olvidándose de Valdovinos, se acordó del moro Abindarráez, cuando el alcaide de Antequera, Rodrigo de Narváez, le prendió y llevó cautivo a su alcaidía. De suerte que, cuando el labrador le volvió a preguntar que cómo estaba y qué sentía, le respondió las mesmas palabras y razones que el cautivo Abencerraje respondía a Rodrigo de Narváez, del mesmo modo que él había leído la historia en La Diana, de Jorge de Montemayor, donde se escribe; aprovechándose della tan a propósito, que el labrador se iba dando al diablo de oír tanta máquina de necedades; por donde conoció que su vecino estaba loco, y dábale priesa a llegar al pueblo, por escusar el enfado que don Quijote le causaba con su larga arenga. Al cabo de lo cual, dijo:

En estas pláticas y en otras semejantes, llegaron al lugar a la hora que anochecía, pero el labrador aguardó a que fuese algo más noche, porque no viesen al molido hidalgo tan mal caballero. Llegada, pues, la hora que le pareció, entró en el pueblo, y en la casa de don Quijote, la cual halló toda alborotada; y estaban en ella el cura y el barbero del lugar, que eran grandes amigos de don Quijote, que estaba diciéndoles su ama a voce llamaba el cura-, de la desgracia de mi señor? Tres días ha que no parecen él, ni el rocín, ni la adarga, ni la lanza ni las armas. ¡Desventurada de mí!, que me doy a entender, y así es ello la verdad como nací para morir, que estos malditos libros de caballerías que él tiene y suele leer tan de ordinario le han vuelto el juicio; que ahora me acuerdo haberle oído decir muchas veces, hablando entre sí, que quería hacerse caballero andante e irse a buscar las aventuras por esos mundos. Encomendados sean a Satanás y a Barrabás tales libros, que así han echado a perder el más delicado entendimiento que había en toda la Mancha.

La sobrina decía lo mesmo, y aun decía más veces le aconteció a mi señor tío estarse leyendo en estos desalmados libros de desventuras dos días con sus noches, al cabo de los cuales, arrojaba el libro de las manos, y ponía mano a la espada y andaba a cuchilladas con las paredes; y cuando estaba muy cansado, decía que había muerto a cuatro gigantes como cuatro torres, y el sudor que sudaba del cansancio decía que era sangre de las feridas que había recebido en la batalla; y bebíase luego un gran jarro de agua fría, y quedaba sano y sosegado, diciendo que aquella agua era una preciosísima bebida que le había traído el sabio Esquife, un grande encantador y amigo suyo. Mas yo me tengo la culpa de todo, que no avisé a vuestras mercedes de los disparates de mi señor tío, para que lo remediaran antes de llegar a lo que ha llegado, y quemaran todos estos descomulgados libros, que tiene muchos, que bien merecen ser abrasados, como si fuesen de herejes.
EOT;
}
